<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-19 at 14:09:56.
 */
class JBSAdminTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JBSAdmin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JBSAdmin;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JBSAdmin::getMediaPlayer
     * @todo   Implement testGetMediaPlayer().
     */
    public function testGetMediaPlayer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JBSAdmin::getAdminsettings
     * @todo   Implement testGetAdminsettings().
     */
    public function testGetAdminsettings() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JBSAdmin::getPermission
     * @todo   Implement testGetPermission().
     */
    public function testGetPermission() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JBSAdmin::commentsPermission
     * @todo   Implement testCommentsPermission().
     */
    public function testCommentsPermission() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JBSAdmin::getShowLevel
     * @todo   Implement testGetShowLevel().
     */
    public function testGetShowLevel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JBSAdmin::showRows
     * @todo   Implement testShowRows().
     */
    public function testShowRows() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JBSAdmin::getUserGroups
     * @todo   Implement testGetUserGroups().
     */
    public function testGetUserGroups() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
