DROP TABLE IF EXISTS `#__bsms_studies`
, `#__bsms_teachers`
, `#__bsms_topics`
, `#__bsms_servers`
, `#__bsms_series`
, `#__bsms_message_type`
, `#__bsms_folders`
, `#__bsms_order`
, `#__bsms_search`
, `#__bsms_media`
, `#__bsms_books`
, `#__bsms_podcast`
, `#__bsms_mimetype`
, `#__bsms_mediafiles`
, `#__bsms_templates`
, `#__bsms_templatecode`
, `#__bsms_comments`
, `#__bsms_admin`
, `#__bsms_studytopics`
, `#__bsms_version`
, `#__bsms_share`
, `#__bsms_locations`
, `#__bsms_timeset`
, `#__bsms_styles`
, `#__bsms_install`
, `#__bsms_schemaVersion`
, `#__bsms_update`;
