<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-19 at 14:07:22.
 */
class JBSFreshInstallTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JBSFreshInstall
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JBSFreshInstall;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JBSFreshInstall::installCSS
     * @todo   Implement testInstallCSS().
     */
    public function testInstallCSS() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
