<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-19 at 12:47:14.
 */
class BiblestudyViewTopicTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var BiblestudyViewTopic
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new BiblestudyViewTopic;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers BiblestudyViewTopic::display
	 * @todo   Implement testDisplay().
	 */
	public function testDisplay()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
