<?php

require_once 'PHPUnit/Framework.php';

require_once JPATH_TESTS_JBS . '/com_biblestudy/admin/biblestudy.script.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-19 at 02:54:13.
 */
class Com_BiblestudyInstallerScriptTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Com_BiblestudyInstallerScript
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Com_BiblestudyInstallerScript;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Com_BiblestudyInstallerScript::preflight
     * @todo   Implement testPreflight().
     */
    public function testPreflight() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Com_BiblestudyInstallerScript::install
     * @todo   Implement testInstall().
     */
    public function testInstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Com_BiblestudyInstallerScript::uninstall
     * @todo   Implement testUninstall().
     */
    public function testUninstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Com_BiblestudyInstallerScript::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Com_BiblestudyInstallerScript::postflight
     * @todo   Implement testPostflight().
     */
    public function testPostflight() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Com_BiblestudyInstallerScript::getParam
     * @todo   Implement testGetParam().
     */
    public function testGetParam() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Com_BiblestudyInstallerScript::setParams
     * @todo   Implement testSetParams().
     */
    public function testSetParams() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Com_BiblestudyInstallerScript::deleteUnexistingFiles
     * @todo   Implement testDeleteUnexistingFiles().
     */
    public function testDeleteUnexistingFiles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Com_BiblestudyInstallerScript::fixMenus
     * @todo   Implement testFixMenus().
     */
    public function testFixMenus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Com_BiblestudyInstallerScript::fixImagePaths
     * @todo   Implement testFixImagePaths().
     */
    public function testFixImagePaths() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Com_BiblestudyInstallerScript::fixemptylanguage
     * @todo   Implement testFixemptylanguage().
     */
    public function testFixemptylanguage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Com_BiblestudyInstallerScript::fixemptyaccess
     * @todo   Implement testFixemptyaccess().
     */
    public function testFixemptyaccess() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
