-- Retire the CD/DVD production set and studytext2 from #__bsms_studies (#1690).
--
-- Seven columns that are declared and never used: no form field, no model, no
-- query, no importer, no view. A production set from when messages shipped on
-- physical media, plus a second study-text field, carried on every row since.
-- Empty on every database available, including one with 827 imported studies.
--
-- ⚠️ One statement per column, deliberately. Joomla's MysqlChangeItem reads only
-- words 3 and 4 of a statement, so a compound
-- `ALTER TABLE x DROP COLUMN a, DROP COLUMN b` registers as a single
-- "DROP COLUMN a" — every clause after the first is neither checked by Database
-- Maintenance nor repairable from it. Same trap as #1664.

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `prod_dvd`;

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `prod_cd`;

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `server_cd`;

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `server_dvd`;

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `image_cd`;

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `image_dvd`;

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `studytext2`;

-- Retire #__bsms_books (#1687).
--
-- 73 rows holding `JBS_BBK_*` language keys, never written by anything, and the
-- same 101-173 -> key map the scripture library already carries in
-- ScriptureHelper::BOOK_KEYS. Every consumer JOINed it and then called Text::_()
-- on the result, so the round trip to the database existed to fetch a
-- translation key. Its `published` column was read only by the two type="SQL"
-- form fields that are now BookList fields.

DROP TABLE IF EXISTS `#__bsms_books`;

-- Retire the flat scripture columns on #__bsms_studies (#1623).
--
-- ⚠️ The backfill must come first, in this file. Joomla runs the SQL update
-- files at step 4 of an update and the postflight migration at step 6, so a
-- site that reaches here unmigrated would lose its references before
-- CwmscriptureMigration ever read them. Statement order inside one file is the
-- only ordering guarantee available.
--
-- Wrapped in a derived table so MySQL materialises the SELECT before inserting:
-- without it, the primary insert would satisfy the secondary's NOT EXISTS and
-- every study's second reference would be dropped on the floor.
--
-- ⚠️ The secondary columns are VARCHAR and really do hold '' and '-1' on real
-- sites, so every read of them is REGEXP-guarded: CAST('' AS SIGNED) raises
-- "Truncated incorrect INTEGER value" under STRICT_TRANS_TABLES and would abort
-- the update.
--
-- reference_text is left empty. It is display text, regenerated by
-- CwmscriptureMigration::migrate() in postflight, where the book
-- names can actually be translated.

INSERT INTO `#__bsms_study_scriptures`
(`study_id`, `ordering`, `booknumber`, `chapter_begin`, `verse_begin`, `chapter_end`, `verse_end`,
 `bible_version`, `reference_text`)
SELECT *
FROM (SELECT `s`.`id`,
             0,
             `s`.`booknumber`,
             COALESCE(`s`.`chapter_begin`, 0),
             COALESCE(`s`.`verse_begin`, 0),
             COALESCE(`s`.`chapter_end`, 0),
             COALESCE(`s`.`verse_end`, 0),
             COALESCE(`s`.`bible_version`, ''),
             ''
      FROM `#__bsms_studies` AS `s`
      WHERE `s`.`booknumber` > 0
        AND NOT EXISTS (SELECT 1
                        FROM `#__bsms_study_scriptures` AS `j`
                        WHERE `j`.`study_id` = `s`.`id`)
      UNION ALL
      SELECT `s`.`id`,
             1,
             CAST(`s`.`booknumber2` AS SIGNED),
             CASE WHEN `s`.`chapter_begin2` REGEXP '^[0-9]+$' THEN CAST(`s`.`chapter_begin2` AS SIGNED) ELSE 0 END,
             CASE WHEN `s`.`verse_begin2` REGEXP '^[0-9]+$' THEN CAST(`s`.`verse_begin2` AS SIGNED) ELSE 0 END,
             CASE WHEN `s`.`chapter_end2` REGEXP '^[0-9]+$' THEN CAST(`s`.`chapter_end2` AS SIGNED) ELSE 0 END,
             CASE WHEN `s`.`verse_end2` REGEXP '^[0-9]+$' THEN CAST(`s`.`verse_end2` AS SIGNED) ELSE 0 END,
             COALESCE(`s`.`bible_version2`, ''),
             ''
      FROM `#__bsms_studies` AS `s`
      WHERE `s`.`booknumber2` REGEXP '^[0-9]+$'
        AND CAST(`s`.`booknumber2` AS SIGNED) > 0
        AND NOT EXISTS (SELECT 1
                        FROM `#__bsms_study_scriptures` AS `j`
                        WHERE `j`.`study_id` = `s`.`id`)) AS `backfill`;

-- ⚠️ One statement per column. MysqlChangeItem reads only words 3 and 4, so a
-- compound ALTER registers as its first clause alone and every later column is
-- invisible to Database Maintenance. Same trap as #1664.

-- ⚠️ Before the columns, and explicitly. Dropping a column that an index
-- covers does not fail: MySQL shrinks `idx_booknumber_published` to
-- `(published)`, which duplicates `idx_state` and leaves an updated site with a
-- schema a fresh install would never produce.

ALTER TABLE `#__bsms_studies`
    DROP INDEX `idx_booknumber_published`;

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `booknumber`;

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `chapter_begin`;

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `verse_begin`;

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `chapter_end`;

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `verse_end`;

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `bible_version`;

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `booknumber2`;

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `chapter_begin2`;

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `verse_begin2`;

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `chapter_end2`;

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `verse_end2`;

ALTER TABLE `#__bsms_studies`
    DROP COLUMN `bible_version2`;

-- A template could have `series_detail_sort` saved as `booknumber`, which
-- Cwmserieslist puts straight into ORDER BY. The column is gone as of this
-- file, so the saved value has to go with it or the series detail page fatals.

UPDATE `#__bsms_templates`
SET `params` = REPLACE(`params`, '"series_detail_sort":"booknumber"', '"series_detail_sort":"studydate"')
WHERE `params` LIKE '%"series_detail_sort":"booknumber"%';
