<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-19 at 03:22:26.
 */
class biblestudyControllerTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var biblestudyController
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new biblestudyController;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers biblestudyController::display
	 * @todo   Implement testDisplay().
	 */
	public function testDisplay()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers biblestudyController::comment
	 * @todo   Implement testComment().
	 */
	public function testComment()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers biblestudyController::commentsEmail
	 * @todo   Implement testCommentsEmail().
	 */
	public function testCommentsEmail()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers biblestudyController::download
	 * @todo   Implement testDownload().
	 */
	public function testDownload()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers biblestudyController::avplayer
	 * @todo   Implement testAvplayer().
	 */
	public function testAvplayer()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers biblestudyController::playHit
	 * @todo   Implement testPlayHit().
	 */
	public function testPlayHit()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers biblestudyController::inlinePlayer
	 * @todo   Implement testInlinePlayer().
	 */
	public function testInlinePlayer()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers biblestudyController::uploadflash
	 * @todo   Implement testUploadflash().
	 */
	public function testUploadflash()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers biblestudyController::upload
	 * @todo   Implement testUpload().
	 */
	public function testUpload()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
