<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-19 at 03:33:53.
 */
class BiblestudyControllerTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var BiblestudyController
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new BiblestudyController;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers BiblestudyController::display
	 * @todo   Implement testDisplay().
	 */
	public function testDisplay()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers BiblestudyController::AjaxTags
	 * @todo   Implement testAjaxTags().
	 */
	public function testAjaxTags()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers BiblestudyController::lookup_topic
	 * @todo   Implement testLookup_topic().
	 */
	public function testLookup_topic()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers BiblestudyController::getFileList
	 * @todo   Implement testGetFileList().
	 */
	public function testGetFileList()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers BiblestudyController::changePlayers
	 * @todo   Implement testChangePlayers().
	 */
	public function testChangePlayers()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers BiblestudyController::changePopup
	 * @todo   Implement testChangePopup().
	 */
	public function testChangePopup()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers BiblestudyController::writeXMLFile
	 * @todo   Implement testWriteXMLFile().
	 */
	public function testWriteXMLFile()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers BiblestudyController::resetHits
	 * @todo   Implement testResetHits().
	 */
	public function testResetHits()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers BiblestudyController::resetDownloads
	 * @todo   Implement testResetDownloads().
	 */
	public function testResetDownloads()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers BiblestudyController::resetPlays
	 * @todo   Implement testResetPlays().
	 */
	public function testResetPlays()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers BiblestudyController::uploadflash
	 * @todo   Implement testUploadflash().
	 */
	public function testUploadflash()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers BiblestudyController::upload
	 * @todo   Implement testUpload().
	 */
	public function testUpload()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
