<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-19 at 03:20:26.
 */
class jbs611InstallTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var jbs611Install
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new jbs611Install;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers jbs611Install::upgrade611
	 * @todo   Implement testUpgrade611().
	 */
	public function testUpgrade611()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
