<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-19 at 13:04:28.
 */
class updatejbs701Test extends PHPUnit_Framework_TestCase {

    /**
     * @var updatejbs701
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new updatejbs701;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers updatejbs701::do701update
     * @todo   Implement testDo701update().
     */
    public function testDo701update() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers updatejbs701::updatetopics
     * @todo   Implement testUpdatetopics().
     */
    public function testUpdatetopics() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers updatejbs701::updateUpdatedb
     * @todo   Implement testUpdateUpdatedb().
     */
    public function testUpdateUpdatedb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
