<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-19 at 03:20:41.
 */
class updatejbsALLTest extends PHPUnit_Framework_TestCase {

    /**
     * @var updatejbsALL
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new updatejbsALL;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers updatejbsALL::doALLupdate
     * @todo   Implement testDoALLupdate().
     */
    public function testDoALLupdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers updatejbsALL::setSchemaVersion
     * @todo   Implement testSetSchemaVersion().
     */
    public function testSetSchemaVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
