<?php
//require_once 'PHPUnit/Framework.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-09 at 18:04:55.
 */
class plgSystemjbspodcastInstallerScriptTest extends PHPUnit_Framework_TestCase {

    /**
     * @var plgSystemjbspodcastInstallerScript
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new plgSystemjbspodcastInstallerScript;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers plgSystemjbspodcastInstallerScript::install
     * @todo   Implement testInstall().
     */
    public function testInstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plgSystemjbspodcastInstallerScript::uninstall
     * @todo   Implement testUninstall().
     */
    public function testUninstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plgSystemjbspodcastInstallerScript::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plgSystemjbspodcastInstallerScript::preflight
     * @todo   Implement testPreflight().
     */
    public function testPreflight() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers plgSystemjbspodcastInstallerScript::postflight
     * @todo   Implement testPostflight().
     */
    public function testPostflight() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
