<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-09 at 18:26:28.
 */
class PlgSystemJbspodcastTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PlgSystemJbspodcast
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PlgSystemJbspodcast;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers PlgSystemJbspodcast::onAfterInitialise
     * @todo   Implement testOnAfterInitialise().
     */
    public function testOnAfterInitialise() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PlgSystemJbspodcast::checktime
     * @todo   Implement testChecktime().
     */
    public function testChecktime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PlgSystemJbspodcast::checkdays
     * @todo   Implement testCheckdays().
     */
    public function testCheckdays() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PlgSystemJbspodcast::updatetime
     * @todo   Implement testUpdatetime().
     */
    public function testUpdatetime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PlgSystemJbspodcast::doPodcast
     * @todo   Implement testDoPodcast().
     */
    public function testDoPodcast() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PlgSystemJbspodcast::doEmail
     * @todo   Implement testDoEmail().
     */
    public function testDoEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
