<?php

/**
 * Part of Proclaim Package
 *
 * @package    Proclaim.Admin
 * @copyright  (C) 2026 CWM Team All rights reserved
 * @license    GNU General Public License version 2 or later; see LICENSE.txt
 * @link       https://www.christianwebministries.org
 * */

namespace CWM\Component\Proclaim\Administrator\Controller;

// phpcs:disable PSR1.Files.SideEffects
\defined('_JEXEC') or die;

// phpcs:enable PSR1.Files.SideEffects

use CWM\Component\Proclaim\Administrator\Controller\Trait\CwmJsonResponseTrait;
use CWM\Component\Proclaim\Administrator\Helper\CwmdbHelper;
use CWM\Component\Proclaim\Administrator\Helper\CwmmigrationHelper;
use CWM\Component\Proclaim\Administrator\Helper\Cwmparams;
use CWM\Component\Proclaim\Administrator\Helper\CwmserverMigrationHelper;
use CWM\Component\Proclaim\Administrator\Helper\CwmtemplatemigrationHelper;
use CWM\Component\Proclaim\Administrator\Lib\Cwmassets;
use CWM\Component\Proclaim\Administrator\Lib\Cwmbackup;
use CWM\Component\Proclaim\Administrator\Lib\Cwmrestore;
use CWM\Component\Proclaim\Administrator\Lib\CwmscriptureMigration;
use CWM\Component\Proclaim\Administrator\Table\CwmtemplatecodeTable;
use Joomla\CMS\Factory;
use Joomla\CMS\Installer\InstallerHelper;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Log\Log;
use Joomla\CMS\MVC\Controller\BaseController;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Session\Session;
use Joomla\Component\Installer\Administrator\Model\DatabaseModel;
use Joomla\Database\DatabaseInterface;
use Joomla\Filesystem\File;
use Joomla\Filesystem\Folder;
use Joomla\Filesystem\Path;

/**
 * Controller for Backup/Restore operations
 *
 * @package  Proclaim.Admin
 * @since    7.0.0
 */
class CwmbackupController extends BaseController
{
    use CwmJsonResponseTrait;

    /**
     * How many statements one import request executes.
     *
     * @var int
     *
     * @since __DEPLOY_VERSION__
     */
    private const int IMPORT_BATCH_SIZE = 50;

    // =========================================================================
    // AJAX Export Methods
    // =========================================================================

    /**
     * Where an import's statements are spooled between requests.
     *
     * @param   string  $sessionId  The import's session id
     *
     * @return  string  Absolute path
     *
     * @throws  \Exception
     * @since   __DEPLOY_VERSION__
     */
    private function importSpoolPath(string $sessionId): string
    {
        $tmp = Factory::getApplication()->get('tmp_path', JPATH_ROOT . '/tmp');

        // The id is generated by prepareImportXHR/uploadImportFileXHR as an md5,
        // but it arrives from the request, so it never reaches the filesystem
        // unsanitised.
        return Path::clean($tmp . '/proclaim_import_' . preg_replace('/[^a-f0-9]/i', '', $sessionId) . '.jsonl');
    }

    /**
     * Delete spools left by imports that never finished.
     *
     * finalizeImportXHR() removes the spool for an import that runs to the end.
     * One that does not -- the browser closed, a request timed out, the user
     * walked away -- leaves a file the size of the dump behind, and nothing
     * else would ever come back for it. A 15 MB dump spools to 16 MB, so a few
     * abandoned attempts are worth noticing.
     *
     * Anything still present after a day is not part of a live import: batches
     * follow each other in seconds.
     *
     * @return  void
     *
     * @throws  \Exception
     * @since   __DEPLOY_VERSION__
     */
    private function sweepStaleSpools(): void
    {
        $tmp = Factory::getApplication()->get('tmp_path', JPATH_ROOT . '/tmp');
        $old = time() - 86400;

        foreach ((array) glob(Path::clean($tmp . '/proclaim_import_*.jsonl')) as $path) {
            if (!\is_string($path) || !is_file($path)) {
                continue;
            }

            if (filemtime($path) < $old) {
                File::delete($path);

                Log::add('Removed an abandoned import spool: ' . basename($path), Log::INFO, 'com_proclaim');
            }
        }
    }

    /**
     * Read one batch of statements back off the spool.
     *
     * Only the lines this batch needs are decoded, so a request costs the same
     * whether the dump held 200 statements or 200,000.
     *
     * @param   string  $sessionId  The import's session id
     * @param   int     $batch      Zero-based batch number
     *
     * @return  string[]  The statements, or an empty array if the spool is gone
     *
     * @throws  \Exception
     * @since   __DEPLOY_VERSION__
     */
    private function readImportSpool(string $sessionId, int $batch): array
    {
        $path = $this->importSpoolPath($sessionId);

        if (!is_file($path)) {
            return [];
        }

        $handle = fopen($path, 'rb');

        if ($handle === false) {
            return [];
        }

        $first   = $batch * self::IMPORT_BATCH_SIZE;
        $last    = $first + self::IMPORT_BATCH_SIZE;
        $line    = 0;
        $queries = [];

        while (($raw = fgets($handle)) !== false) {
            if ($line >= $first && $line < $last) {
                try {
                    $decoded = json_decode($raw, true, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    // A truncated spool line means the statement is unrecoverable.
                    // Surfacing it beats running the rest and calling it a success.
                    Log::add(
                        'Import spool line ' . $line . ' could not be decoded: ' . $e->getMessage(),
                        Log::ERROR,
                        'com_proclaim'
                    );

                    $decoded = null;
                }

                if (\is_string($decoded)) {
                    $queries[] = $decoded;
                }
            }

            $line++;

            if ($line >= $last) {
                break;
            }
        }

        fclose($handle);

        return $queries;
    }

    /**
     * Get a list of tables for AJAX export
     *
     * @return void
     *
     * @throws \Exception
     * @since 10.1.0
     */
    public function getExportTablesXHR(): void
    {
        // Check for request forgeries
        if (!Session::checkToken('get') && !Session::checkToken()) {
            $this->sendJsonResponse(false, Text::_('JINVALID_TOKEN'));
        }

        $app    = Factory::getApplication();
        $config = $app->getConfig();

        // Create a unique export ID for this session
        $exportId = md5(uniqid((string) mt_rand(), true));
        $tmpPath  = $config->get('tmp_path') . '/proclaim_export_' . $exportId . '.sql';

        // Initialize an empty file
        file_put_contents($tmpPath, '');

        $tables     = CwmdbHelper::getOwnObjects();
        $tableNames = array_column($tables, 'name');

        // Add virtual "tables" for component config, scheduled tasks, and
        // per-record/component-level asset permissions. Virtual tables are
        // chunk-exempt and always dumped in one pass.
        $tableNames[] = '_component_config';
        $tableNames[] = '_scheduled_tasks';
        $tableNames[] = '_proclaim_assets';

        // Build table info with row counts for chunked export
        $backup    = new Cwmbackup();
        $tableInfo = [];

        foreach ($tableNames as $name) {
            $rows = 0;

            if (!str_starts_with($name, '_')) {
                try {
                    $rows = $backup->getTableRowCount($name);
                } catch (\Exception $e) {
                    Log::add('Failed to count rows for ' . $name . ': ' . $e->getMessage(), Log::WARNING, 'com_proclaim');
                }
            }

            $tableInfo[] = ['name' => $name, 'rows' => $rows];
        }

        // Return the export ID so it can be passed to later calls
        $this->sendJsonResponse(true, '', ['tables' => $tableInfo, 'exportId' => $exportId]);
    }

    /**
     * Export a single table via AJAX
     *
     * @return void
     *
     * @throws \Exception
     * @since 10.1.0
     */
    public function exportTableXHR(): void
    {
        // Check for request forgeries
        if (!Session::checkToken('get') && !Session::checkToken()) {
            $this->sendJsonResponse(false, Text::_('JINVALID_TOKEN'));
        }

        $app      = Factory::getApplication();
        $input    = $app->getInput();
        $config   = $app->getConfig();
        $table    = $input->get('table', '', 'string');
        $exportId = $input->get('exportId', '', 'string');
        $offset   = $input->getInt('offset', -1);
        $limit    = $input->getInt('limit', 0);

        if (empty($table)) {
            $this->sendJsonResponse(false, 'No table specified');
        }

        if (empty($exportId)) {
            $this->sendJsonResponse(false, 'No export ID specified');
        }

        // Build the temp file path from the export ID
        $tmpPath = $config->get('tmp_path') . '/proclaim_export_' . $exportId . '.sql';

        if (!is_file($tmpPath)) {
            $this->sendJsonResponse(false, 'Export file not found. Please start again.');
        }

        $backup = new Cwmbackup();

        // Chunked export: offset >= 0 and limit > 0 triggers row-range mode
        if ($offset >= 0 && $limit > 0 && !str_starts_with($table, '_')) {
            $tableData = '';

            // First chunk includes DDL (DROP + CREATE)
            if ($offset === 0) {
                $tableData .= $backup->getExportTableStructure($table);
            }

            $tableData .= $backup->getExportTableRows($table, $offset, $limit);

            // Add separator after the last chunk
            $rowCount = $backup->getTableRowCount($table);

            if ($offset + $limit >= $rowCount) {
                $tableData .= "\n-- --------------------------------------------------------\n\n";
            }
        } else {
            // Full export (small tables or virtual tables)
            $tableData = $backup->getExportTableData($table);
        }

        // Append to temp file
        if (file_put_contents($tmpPath, $tableData, FILE_APPEND) === false) {
            $this->sendJsonResponse(false, 'Failed to write export data');
        }

        $this->sendJsonResponse(true, '', ['table' => $table, 'size' => \strlen($tableData)]);
    }

    /**
     * Finalize export and create a download file
     *
     * @return void
     *
     * @throws \Exception
     * @since 10.1.0
     */
    public function finalizeExportXHR(): void
    {
        $this->registerFatalErrorShutdownHandler();

        try {
            // Check for request forgeries
            if (!Session::checkToken('get') && !Session::checkToken()) {
                $this->sendJsonResponse(false, Text::_('JINVALID_TOKEN'));
            }

            $app      = Factory::getApplication();
            $input    = $app->getInput();
            $mode     = $input->get('mode', 'download', 'string');
            $exportId = $input->get('exportId', '', 'string');
            $session  = $app->getSession();
            $config   = $app->getConfig();

            if (empty($exportId)) {
                $this->sendJsonResponse(false, 'No export ID specified');
            }

            // Build the temp file path from the export ID
            $tmpExportPath = $config->get('tmp_path') . '/proclaim_export_' . $exportId . '.sql';

            if (!is_file($tmpExportPath)) {
                $this->sendJsonResponse(false, 'Export file not found. Please start again.');
            }

            // Generate filename using standardized method
            $filename = Cwmbackup::generateBackupFilename();

            // Check if compression is requested (default: yes)
            $compress = $input->getInt('jbs_compress', 1);

            if ($mode === 'save') {
                // Save to back up folder
                $backupDir = JPATH_SITE . '/media/com_proclaim/backup/';

                if (!is_dir($backupDir)) {
                    Folder::create($backupDir);
                }

                $path = $backupDir . $filename;

                // Move the temp file to backup location
                if (!rename($tmpExportPath, $path)) {
                    // Fallback to copy + delete
                    if (!copy($tmpExportPath, $path)) {
                        $this->sendJsonResponse(false, 'Failed to write backup file');
                    }
                    File::delete($tmpExportPath);
                }

                // Compress the file if requested
                if ($compress) {
                    $zipPath  = $this->compressBackupFile($path);
                    $path     = $zipPath;
                    $filename = basename($zipPath);
                }

                // Clean up old backups
                $backup = new Cwmbackup();
                $backup->updatefiles(Cwmparams::getAdmin()->params);

                $this->sendJsonResponse(true, '', ['filename' => $filename, 'path' => $path]);
            } else {
                // Rename temp file for download
                $downloadPath = $config->get('tmp_path') . '/' . $filename;

                if (!rename($tmpExportPath, $downloadPath)) {
                    // Fallback to copy + delete
                    if (!copy($tmpExportPath, $downloadPath)) {
                        $this->sendJsonResponse(false, 'Failed to prepare download file');
                    }
                    File::delete($tmpExportPath);
                }

                // Compress the file if requested
                if ($compress) {
                    $zipPath      = $this->compressBackupFile($downloadPath);
                    $downloadPath = $zipPath;
                    $filename     = basename($zipPath);
                }

                // Store path in session for download (needed for the download redirect)
                $session->set('proclaim_download_file', $downloadPath, 'CWM');

                // Return URL for download
                $downloadUrl = Route::_('index.php?option=com_proclaim&task=cwmbackup.downloadExportXHR&' . Session::getFormToken() . '=1', false);

                $this->sendJsonResponse(true, '', ['filename' => $filename, 'downloadUrl' => $downloadUrl]);
            }
        } catch (\Exception $e) {
            $this->sendJsonResponse(false, 'Export error: ' . $e->getMessage());
        }
    }

    /**
     * Download the exported file
     *
     * @return void
     *
     * @throws \Exception
     * @since 10.1.0
     */
    public function downloadExportXHR(): void
    {
        // Check for request forgeries
        if (!Session::checkToken('get') && !Session::checkToken()) {
            throw new \RuntimeException(Text::_('JINVALID_TOKEN'));
        }

        $app     = Factory::getApplication();
        $session = $app->getSession();

        $filePath = $session->get('proclaim_download_file', '', 'CWM');

        if (empty($filePath) || !is_file($filePath)) {
            throw new \RuntimeException('Download file not found');
        }

        // Clear session
        $session->set('proclaim_download_file', '', 'CWM');

        // Determine MIME type based on file extension
        $mimeType = str_ends_with(strtolower($filePath), '.zip') ? 'application/zip' : 'text/x-sql';

        // Output file
        $backup = new Cwmbackup();
        $backup->outputFile($filePath, basename($filePath), $mimeType);

        // Clean up
        File::delete($filePath);

        $app->close();
    }

    // =========================================================================
    // AJAX Import Methods
    // =========================================================================

    /**
     * Upload import file via AJAX
     *
     * @return void
     *
     * @throws \Exception
     * @since 10.1.0
     */
    public function uploadImportFileXHR(): void
    {
        // Check for request forgeries
        if (!Session::checkToken('get') && !Session::checkToken()) {
            $this->sendJsonResponse(false, Text::_('JINVALID_TOKEN'));
        }

        $app      = Factory::getApplication();
        $input    = $app->getInput();
        $userfile = $input->files->get('importdb', null, 'raw');

        if (!\is_array($userfile) || $userfile['error'] || $userfile['size'] < 1) {
            $this->sendJsonResponse(false, Text::_('JBS_IBM_ERROR_UPLOAD_FAILED'));
        }

        // Move uploaded file to tmp
        $config   = $app->getConfig();
        $tmpPath  = $config->get('tmp_path') . '/' . $userfile['name'];

        if (!File::upload($userfile['tmp_name'], $tmpPath, false, true)) {
            $this->sendJsonResponse(false, 'Failed to move uploaded file');
        }

        // Handle ZIP files
        if (str_ends_with(strtolower($tmpPath), '.zip')) {
            $package = InstallerHelper::unpack($tmpPath, true);

            if (!isset($package['dir'])) {
                $this->sendJsonResponse(false, 'Failed to extract ZIP file');
            }

            // Find SQL file in extracted directory
            $files = Folder::files($package['dir'], '\.sql$', true, true);

            if (empty($files)) {
                $this->sendJsonResponse(false, 'No SQL file found in archive');
            }

            $tmpPath = $files[0];
        }

        // Generate session ID and store a file path
        $sessionId = md5(uniqid((string) mt_rand(), true));
        $session   = $app->getSession();
        $session->set('proclaim_import_' . $sessionId, $tmpPath, 'CWM');

        $this->sendJsonResponse(true, '', ['sessionId' => $sessionId]);
    }

    /**
     * Prepare import from backup folder or tmp folder
     *
     * @return void
     *
     * @throws \Exception
     * @since 10.1.0
     */
    public function prepareImportXHR(): void
    {
        // Check for request forgeries
        if (!Session::checkToken('get') && !Session::checkToken()) {
            $this->sendJsonResponse(false, Text::_('JINVALID_TOKEN'));
        }

        $app    = Factory::getApplication();
        $input  = $app->getInput();
        $type   = $input->get('type', '', 'string');
        $source = $input->get('source', '', 'string');

        if (empty($type) || empty($source)) {
            $this->sendJsonResponse(false, 'Missing type or source parameter');
        }

        $filePath = '';

        if ($type === 'backup') {
            // From backup folder
            $filePath = JPATH_SITE . '/media/com_proclaim/backup/' . basename($source);
        } elseif ($type === 'folder') {
            // From tmp folder
            $filePath = Path::clean($source);
        }

        if (!is_file($filePath)) {
            $this->sendJsonResponse(false, Text::_('JBS_IBM_NOT_DB'));
        }

        // Generate session ID and store a file path
        $sessionId = md5(uniqid((string) mt_rand(), true));
        $session   = $app->getSession();
        $session->set('proclaim_import_' . $sessionId, $filePath, 'CWM');

        $this->sendJsonResponse(true, '', ['sessionId' => $sessionId]);
    }

    /**
     * Get import file info (for progress tracking)
     *
     * @return void
     *
     * @throws \Exception
     * @since 10.1.0
     */
    public function getImportInfoXHR(): void
    {
        // Check for request forgeries
        if (!Session::checkToken('get') && !Session::checkToken()) {
            $this->sendJsonResponse(false, Text::_('JINVALID_TOKEN'));
        }

        $app       = Factory::getApplication();
        $input     = $app->getInput();
        $sessionId = $input->get('sessionId', '', 'string');
        $session   = $app->getSession();

        $filePath = $session->get('proclaim_import_' . $sessionId, '', 'CWM');

        if (empty($filePath) || !is_file($filePath)) {
            $this->sendJsonResponse(false, 'Import file not found');
        }

        // Read and validate a file
        $content = file_get_contents($filePath);

        if ($content === false) {
            $this->sendJsonResponse(false, Text::_('JBS_INS_ERROR_SQL_READBUFFER'));
        }

        // Validate it's a Proclaim backup
        $isnot = substr_count($content, '#__bsms_studies');

        if ($isnot === 0) {
            $this->sendJsonResponse(false, Text::_('JBS_IBM_NOT_DB'));
        }

        // Splitting is the one step whose cost is the size of the whole file,
        // and it is measured in seconds per megabyte. The browser is told to
        // wait; PHP has to be told as well, or a large dump dies here on a
        // default 30- or 60-second limit.
        if (\function_exists('set_time_limit')) {
            @set_time_limit(600);
        }

        // A dump written by anything other than Cwmbackup lists generated
        // columns like any other, and MySQL rejects every INSERT that names
        // one. Rewrite them before the split so the demoted definitions and
        // the statements that put them back travel together.
        $normalised = Cwmrestore::normaliseGeneratedColumns($content);

        // Split into queries. Cwmrestore::splitSqlFast() is a port of the core
        // splitter that returns the same statements without allocating four
        // short strings per character; see its docblock.
        $queries = Cwmrestore::splitSqlFast($normalised['sql']);

        // The generated columns go back on once every row is loaded.
        foreach ($normalised['restore'] as $restore) {
            $queries[] = $restore;
        }

        // Spool the statements to disk, one JSON-encoded statement per line.
        //
        // ⚠️ These used to go in the session. #__session.data is a mediumtext,
        // and writing a row that size also needs max_allowed_packet above it,
        // so a dump of any real size failed the session write silently — after
        // this method had already told the browser how many batches to expect.
        // The next request found nothing and reported "No queries found in
        // session". JSON encoding is what makes the line-per-statement format
        // safe: it escapes the newlines inside a statement.
        $this->sweepStaleSpools();

        $spoolPath = $this->importSpoolPath($sessionId);
        $spool     = fopen($spoolPath, 'wb');

        if ($spool === false) {
            $this->sendJsonResponse(false, Text::_('JBS_IBM_SPOOL_FAILED'));
        }

        foreach ($queries as $query) {
            fwrite($spool, json_encode($query, JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR) . "\n");
        }

        fclose($spool);

        // Only the count and the path go in the session now.
        $session->set('proclaim_import_count_' . $sessionId, \count($queries), 'CWM');

        $totalBatches = (int) ceil(\count($queries) / self::IMPORT_BATCH_SIZE);

        $this->sendJsonResponse(true, '', [
            'totalQueries' => \count($queries),
            'totalBatches' => $totalBatches,
            'batchSize'    => self::IMPORT_BATCH_SIZE,
        ]);
    }

    /**
     * Import a batch of SQL queries
     *
     * @return void
     *
     * @throws \Exception
     * @since 10.1.0
     */
    public function importBatchXHR(): void
    {
        // Check for request forgeries
        if (!Session::checkToken('get') && !Session::checkToken()) {
            $this->sendJsonResponse(false, Text::_('JINVALID_TOKEN'));
        }

        $app       = Factory::getApplication();
        $input     = $app->getInput();
        $sessionId = $input->get('sessionId', '', 'string');
        $batch     = $input->get('batch', 0, 'int');
        $session   = $app->getSession();

        $batchQueries = $this->readImportSpool($sessionId, $batch);

        if ($batchQueries === []) {
            $this->sendJsonResponse(false, Text::_('JBS_IBM_SPOOL_MISSING'));
        }

        $db = Factory::getContainer()->get(DatabaseInterface::class);

        // For the first batch, drop Proclaim's own tables.
        //
        // ⚠️ This used to carry `$preserve = ['#__bsms_bible_verses']`, meaning
        // to keep downloaded bible data across a restore. It could not work.
        // The export wrote a `DROP TABLE IF EXISTS` for every table it dumped,
        // including that one, so skipping the drop here only deferred it by a
        // few statements — the backup's own SQL dropped and recreated the table
        // from the snapshot. The intent was right and the mechanism was not.
        //
        // getOwnObjects() excludes the whole shared scripture stack, which is
        // the library's to manage -- as it already is on uninstall. Nothing
        // here drops them, and every statement below is put through
        // Cwmrestore::classifyStatement(), so an older backup still carrying
        // those tables cannot reach them either.
        if ($batch === 0) {
            $objects = CwmdbHelper::getOwnObjects();

            foreach ($objects as $object) {
                $dropper = 'DROP TABLE IF EXISTS ' . $db->quoteName($object['name']);
                $db->setQuery($dropper);
                $db->execute();
            }
        }

        // Execute batch queries.
        //
        // A failure here is reported, not just logged. Batch 0 has already
        // dropped all of Proclaim's tables, so a restore that quietly gives up
        // partway leaves the site emptier than it found it -- and the caller
        // used to be told the batch succeeded regardless of how many
        // statements inside it had not.
        $executed = 0;
        $skipped  = 0;
        $errors   = [];

        foreach ($batchQueries as $query) {
            $query = trim($query);

            if ($query === '' || $query[0] === '#') {
                continue;
            }

            $verdict = Cwmrestore::classifyStatement($query);

            if ($verdict !== Cwmrestore::STATEMENT_ALLOWED) {
                $skipped++;

                if ($verdict === Cwmrestore::STATEMENT_REJECTED) {
                    Log::add(
                        'Import skipped a statement targeting a table outside Proclaim: ' . substr($query, 0, 120),
                        Log::WARNING,
                        'com_proclaim'
                    );
                }

                continue;
            }

            try {
                $db->setQuery($query);
                $db->execute();
                $executed++;
            } catch (\Exception $e) {
                $errors[] = [
                    'statement' => substr(preg_replace('/\s+/', ' ', $query) ?? '', 0, 160),
                    'error'     => $e->getMessage(),
                ];

                Log::add('Import query error: ' . $e->getMessage(), Log::ERROR, 'com_proclaim');
            }
        }

        $this->sendJsonResponse(true, '', [
            'batch'     => $batch,
            'processed' => \count($batchQueries),
            'executed'  => $executed,
            'skipped'   => $skipped,
            'failed'    => \count($errors),
            'errors'    => $errors,
        ]);
    }

    /**
     * Run a single post-restore data fix step via AJAX.
     *
     * Called sequentially by the JS after batch import completes.
     * Each step is independent — failure of one does not block others.
     *
     * @return void
     *
     * @throws \Exception
     * @since 10.2.0
     */
    public function postRestoreStepXHR(): void
    {
        $this->registerFatalErrorShutdownHandler();

        try {
            if (!Session::checkToken('get') && !Session::checkToken()) {
                $this->sendJsonResponse(false, Text::_('JINVALID_TOKEN'));
            }

            $app  = Factory::getApplication();
            $step = $app->getInput()->getInt('step', -1);

            // Give each step up to 5 minutes
            if (\function_exists('set_time_limit')) {
                set_time_limit(300);
            }

            $labels = [
                'Fixing teacher aliases',
                'Populating study-teacher links',
                'Migrating scripture references',
                'Seeding Bible translations',
                'Fixing media file legacy paths',
                'Migrating template defaults',
            ];

            $totalSteps = \count($labels);

            if ($step < 0 || $step >= $totalSteps) {
                $this->sendJsonResponse(false, 'Invalid post-restore step: ' . $step);
            }

            match ($step) {
                0 => CwmmigrationHelper::fixTeacherAliases(),
                1 => CwmmigrationHelper::populateStudyTeachers(),
                2 => CwmscriptureMigration::migrate(),
                3 => CwmmigrationHelper::seedBibleTranslations(),
                4 => CwmmigrationHelper::fixMediafileLegacyPaths(),
                5 => (new CwmtemplatemigrationHelper())->migrateAll(),
            };

            Log::add('Post-restore step ' . $step . ' completed: ' . $labels[$step], Log::INFO, 'com_proclaim');

            $this->sendJsonResponse(true, '', [
                'step'       => $step,
                'label'      => $labels[$step],
                'totalSteps' => $totalSteps,
            ]);
        } catch (\Exception $e) {
            $this->sendJsonResponse(false, 'Post-restore step error: ' . $e->getMessage());
        }
    }

    /**
     * Finalize import-fix assets and ownership
     *
     * @return void
     *
     * @throws \Exception
     * @since 10.1.0
     */
    public function finalizeImportXHR(): void
    {
        // Try to increase the memory limit (best-effort may fail on shared hosting)
        $currentLimit = $this->getMemoryLimitBytes();
        $targetLimit  = 512 * 1024 * 1024; // 512M

        if ($currentLimit > 0 && $currentLimit < $targetLimit) {
            // Try progressive increases - some hosts allow modest increases but not large ones
            foreach (['256M', '384M', '512M'] as $tryLimit) {
                @ini_set('memory_limit', $tryLimit);
            }
        }

        // Suppress error display and capture any output
        $previousErrorReporting = error_reporting(E_ALL);
        $previousDisplayErrors  = \ini_get('display_errors');
        ini_set('display_errors', '0');
        ob_start();

        $this->registerFatalErrorShutdownHandler();

        try {
            // Check for request forgeries
            if (!Session::checkToken('get') && !Session::checkToken()) {
                $this->sendJsonResponse(false, Text::_('JINVALID_TOKEN'));
            }

            $app           = Factory::getApplication();
            $input         = $app->getInput();
            $sessionId     = $input->get('sessionId', '', 'string');
            $skipAssetFix  = $input->get('skipAssetFix', '0', 'string') === '1';
            $dataFixesRun  = $input->get('dataFixesRun', '0', 'string') === '1';
            $session       = $app->getSession();

            // Retrieve and clean up the import file path before clearing session
            $importFilePath = $session->get('proclaim_import_' . $sessionId, '', 'CWM');

            // Clean up session data
            $session->set('proclaim_import_' . $sessionId, '', 'CWM');
            $session->set('proclaim_import_count_' . $sessionId, '', 'CWM');

            // And the statement spool this import wrote to disk.
            $spoolPath = $this->importSpoolPath($sessionId);

            if (is_file($spoolPath)) {
                File::delete($spoolPath);
            }

            // Reset schema version and run migrations so tables/columns added
            // after the backup was created get applied (e.g. bible_translations).
            $schemaFixed = $this->fixSchemaAfterRestore();

            // Run post-restore data fixes unless already run via postRestoreStepXHR
            if (!$dataFixesRun) {
                $this->runPostRestoreDataFixes();
            }

            // Correct AUTO_INCREMENT counters that may be stale from backup
            $autoIncrementFixes = Cwmrestore::correctAutoIncrements();

            // Fix assets using the centralised Cwmassets engine (unless skipped for testing)
            if (!$skipAssetFix) {
                Cwmassets::fixAllAssets();
            } else {
                Log::add('Asset fix skipped (testing mode)', Log::INFO, 'com_proclaim');
            }

            // Recreate templatecode PHP files from database records
            $templatecodesCreated = $this->recreateTemplatecodeFiles();

            // Verify restore integrity
            $integrity = Cwmrestore::verifyRestoreIntegrity();
            Log::add(
                \sprintf(
                    'Restore verification: %d tables, %d tasks, config %s',
                    $integrity['tables'],
                    $integrity['tasks'],
                    $integrity['config'] ? 'OK' : 'missing'
                ),
                Log::INFO,
                'com_proclaim'
            );

            // Clean up tmp files left by the import
            $this->cleanupImportTmpFiles($importFilePath);

            // What the restore could not do for the user. A 9.x backup arrives
            // with every server typed `legacy`, and the restore has no business
            // re-pointing thousands of media rows without being asked -- but it
            // should not report itself finished without saying so either.
            $pendingMigration = CwmserverMigrationHelper::countPendingMigration();

            $this->sendJsonResponse(true, Text::_('JBS_CMN_OPERATION_SUCCESSFUL'), [
                'templatecodes_created' => $templatecodesCreated,
                'tables_restored'       => $integrity['tables'],
                'tasks_restored'        => $integrity['tasks'],
                'config_restored'       => $integrity['config'],
                'auto_increment_fixes'  => $autoIncrementFixes,
                'pending_migration'     => $pendingMigration,
            ]);
        } catch (\Exception $e) {
            $this->sendJsonResponse(false, 'Import finalize error: ' . $e->getMessage());
        }
    }

    /**
     * Reset the schema version and run Joomla's DatabaseModel::fix() so that
     * SQL update files created after the backup run against the restored data.
     *
     * The restore replaces all bsms_* tables with backup data, but #__schemas
     * (a Joomla core table) keeps the pre-restore version. Without a reset,
     * fix() thinks the schema is already current and skips creating tables
     * that were added after the backup (e.g. bible_translations).
     *
     * @return  bool  True if schema was repaired successfully
     *
     * @since   10.1.0
     */
    private function fixSchemaAfterRestore(): bool
    {
        $db = Factory::getContainer()->get(DatabaseInterface::class);

        // Find the Proclaim extension ID
        $query = $db->createQuery();
        $query->select($db->quoteName('extension_id'))
            ->from($db->quoteName('#__extensions'))
            ->where($db->quoteName('element') . ' = ' . $db->quote('com_proclaim'));
        $db->setQuery($query);
        $cid = (int) $db->loadResult();

        if (!$cid) {
            Log::add('Cannot fix schema: com_proclaim not found in extensions', Log::WARNING, 'com_proclaim');

            return false;
        }

        // Reset #__schemas to force all update files to re-run
        $query = $db->createQuery();
        $query->delete($db->quoteName('#__schemas'))
            ->where($db->quoteName('extension_id') . ' = ' . $cid);
        $db->setQuery($query);
        $db->execute();

        $query = $db->createQuery();
        $query->insert($db->quoteName('#__schemas'))
            ->columns([$db->quoteName('extension_id'), $db->quoteName('version_id')])
            ->values($cid . ', ' . $db->quote('0.0.0'));
        $db->setQuery($query);
        $db->execute();

        // Run Joomla's schema fixer — processes all SQL update files in order
        $databaseModel = new DatabaseModel();
        $databaseModel->fix([$cid]);

        Log::add('Schema version reset and migrations re-applied after restore', Log::INFO, 'com_proclaim');

        return true;
    }

    // =========================================================================
    // Helper Methods
    // =========================================================================

    /**
     * Get PHP memory limit in bytes
     *
     * @return int Memory limit in bytes, or -1 if unlimited
     *
     * @since 10.1.0
     */
    private function getMemoryLimitBytes(): int
    {
        $limit = \ini_get('memory_limit');

        if ($limit === '-1') {
            return -1; // Unlimited
        }

        $value = (int) $limit;
        $unit  = strtoupper(substr($limit, -1));

        switch ($unit) {
            case 'G':
                $value *= 1024 * 1024 * 1024;
                break;
            case 'M':
                $value *= 1024 * 1024;
                break;
            case 'K':
                $value *= 1024;
                break;
        }

        return $value;
    }

    /**
     * Recreate templatecode PHP files from database records
     *
     * After import, the templatecode table has the PHP code but the actual
     * template files in the tmpl directories don't exist. This method
     * recreates them from the database records.
     *
     * @return int Number of templatecode files created
     *
     * @since 10.1.0
     */
    private function recreateTemplatecodeFiles(): int
    {
        $db      = Factory::getContainer()->get(DatabaseInterface::class);
        $created = 0;

        try {
            // Get all templatecode records
            $query = $db->createQuery();
            $query->select($db->quoteName(['id', 'type', 'filename', 'templatecode']))
                ->from($db->quoteName('#__bsms_templatecode'))
                ->where($db->quoteName('published') . ' = 1');
            $db->setQuery($query);
            $records = $db->loadObjectList();

            if (empty($records)) {
                Log::add('No templatecode records to recreate', Log::INFO, 'com_proclaim');

                return 0;
            }

            // ⚠️ Taken from CwmtemplatecodeTable, not copied. This map used to
            // live here as well, and both copies still named the capitalised
            // directories the package stopped shipping in 2022 -- so a restore
            // rewrote layouts a case-sensitive host would never read.
            foreach ($records as $record) {
                $type = (int) $record->type;

                if (!isset(CwmtemplatecodeTable::LAYOUT_DIRECTORIES[$type])) {
                    Log::add('Unknown templatecode type: ' . $type . ' for ID ' . $record->id, Log::WARNING, 'com_proclaim');
                    continue;
                }

                $directory = JPATH_ROOT . '/' . CwmtemplatecodeTable::LAYOUT_DIRECTORIES[$type] . '/';
                $filename  = 'default_' . $record->filename . '.php';
                $filepath  = $directory . $filename;

                // Ensure directory exists
                if (!is_dir($directory)) {
                    Log::add('Templatecode directory does not exist: ' . $directory, Log::WARNING, 'com_proclaim');
                    continue;
                }

                // Prepare content - ensure security check is present
                $content       = $record->templatecode;
                $securityCheck = "defined('_JEXEC') or die;";

                if (strpos($content, $securityCheck) === false) {
                    $content = "<?php\n" . $securityCheck . "\n" . $content;
                }

                // Write the file
                if (File::write($filepath, $content)) {
                    $created++;
                    Log::add('Created templatecode file: ' . $filepath, Log::INFO, 'com_proclaim');
                } else {
                    Log::add('Failed to create templatecode file: ' . $filepath, Log::WARNING, 'com_proclaim');
                }
            }

            Log::add('Recreated ' . $created . ' templatecode files', Log::INFO, 'com_proclaim');
        } catch (\Exception $e) {
            Log::add('Error recreating templatecode files: ' . $e->getMessage(), Log::ERROR, 'com_proclaim');
        }

        return $created;
    }

    /**
     * Run post-restore data fixes that Joomla's ChangeSet cannot handle.
     *
     * These are PHP-level migrations for INSERT/UPDATE/DELETE operations
     * that the SQL DDL-only ChangeSet skips.
     *
     * @return  void
     *
     * @since   10.1.0
     */
    private function runPostRestoreDataFixes(): void
    {
        try {
            CwmmigrationHelper::fixTeacherAliases();
        } catch (\Exception $e) {
            Log::add('Post-restore teacher alias fix failed: ' . $e->getMessage(), Log::WARNING, 'com_proclaim');
        }

        try {
            CwmmigrationHelper::populateStudyTeachers();
        } catch (\Exception $e) {
            Log::add('Post-restore study-teacher population failed: ' . $e->getMessage(), Log::WARNING, 'com_proclaim');
        }

        // Populate scripture junction table from legacy flat columns
        try {
            CwmscriptureMigration::migrate();
        } catch (\Exception $e) {
            Log::add('Post-restore scripture migration failed: ' . $e->getMessage(), Log::WARNING, 'com_proclaim');
        }

        try {
            CwmmigrationHelper::seedBibleTranslations();
        } catch (\Exception $e) {
            Log::add('Post-restore bible translation seed failed: ' . $e->getMessage(), Log::WARNING, 'com_proclaim');
        }

        // Fix legacy image paths in mediafile params
        try {
            CwmmigrationHelper::fixMediafileLegacyPaths();
        } catch (\Exception $e) {
            Log::add('Post-restore mediafile path fix failed: ' . $e->getMessage(), Log::WARNING, 'com_proclaim');
        }

        try {
            $migration = new CwmtemplatemigrationHelper();
            $migration->migrateAll();
        } catch (\Exception $e) {
            Log::add('Post-restore template defaults merge failed: ' . $e->getMessage(), Log::WARNING, 'com_proclaim');
        }
    }

    /**
     * Clean up temporary files left by the import process.
     *
     * Removes the uploaded SQL file, any extracted ZIP directory,
     * and stale proclaim_export_* files from previous exports.
     *
     * @param   string  $importFilePath  Path to the import SQL file (from session)
     *
     * @return  void
     *
     * @since   10.1.0
     */
    private function cleanupImportTmpFiles(string $importFilePath): void
    {
        $config  = Factory::getApplication()->getConfig();
        $tmpPath = $config->get('tmp_path');

        // Delete the uploaded/extracted SQL file
        if (!empty($importFilePath) && is_file($importFilePath)) {
            try {
                File::delete($importFilePath);
            } catch (\Exception $e) {
                Log::add('Failed to delete import file: ' . $e->getMessage(), Log::WARNING, 'com_proclaim');
            }

            // If the SQL was inside an extracted directory, clean that too
            $extractDir = \dirname($importFilePath);

            if ($extractDir !== $tmpPath && str_starts_with($extractDir, $tmpPath) && is_dir($extractDir)) {
                try {
                    Folder::delete($extractDir);
                } catch (\Exception $e) {
                    Log::add('Failed to delete extract dir: ' . $e->getMessage(), Log::WARNING, 'com_proclaim');
                }
            }
        }

        // Clean up any stale proclaim_export_*.sql files from previous exports
        try {
            $staleFiles = Folder::files($tmpPath, '^proclaim_export_.*\.sql$', false, true);

            foreach ($staleFiles as $staleFile) {
                // Only delete files older than 1 hour
                if (filemtime($staleFile) < time() - 3600) {
                    File::delete($staleFile);
                }
            }
        } catch (\Exception $e) {
            Log::add('Failed to clean stale export files: ' . $e->getMessage(), Log::WARNING, 'com_proclaim');
        }
    }

    /**
     * Compress a backup file into a ZIP archive
     *
     * @param   string  $sqlFilePath  Path to the SQL file to compress
     *
     * @return string Path to the created ZIP file
     *
     * @throws \RuntimeException If ZIP creation fails
     * @since 10.1.0
     */
    private function compressBackupFile(string $sqlFilePath): string
    {
        $zipPath = $sqlFilePath . '.zip';
        $zip     = new \ZipArchive();

        // Create the ZIP file
        if ($zip->open($zipPath, \ZipArchive::CREATE) !== true) {
            throw new \RuntimeException("Cannot create ZIP file: {$zipPath}");
        }

        // Add the SQL file to the ZIP
        $zip->addFile($sqlFilePath, basename($sqlFilePath));
        $zip->close();

        // Delete the original SQL file
        File::delete($sqlFilePath);

        Log::add('Compressed backup file: ' . basename($zipPath), Log::INFO, 'com_proclaim');

        return $zipPath;
    }

    /**
     * Register a shutdown handler that reports a PHP fatal error as JSON
     * instead of letting it surface as a blank/HTML response to an XHR caller.
     *
     * @return void
     *
     * @since 10.5.6
     */
    private function registerFatalErrorShutdownHandler(): void
    {
        register_shutdown_function(function () {
            $error = error_get_last();

            if ($error !== null && \in_array($error['type'], [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR], true)) {
                while (ob_get_level()) {
                    ob_end_clean();
                }
                header('Content-Type: application/json; charset=utf-8');
                echo json_encode([
                    'success' => false,
                    'message' => 'PHP Fatal: ' . $error['message'] . ' in ' . $error['file'] . ':' . $error['line'],
                    'data'    => [],
                ], JSON_THROW_ON_ERROR);
            }
        });
    }
}
