<?php

/**
 * Part of Proclaim Package
 *
 * @package    Proclaim.Admin
 * @copyright  (C) 2026 CWM Team All rights reserved
 * @license    GNU General Public License version 2 or later; see LICENSE.txt
 * @link       https://www.christianwebministries.org
 */

namespace CWM\Component\Proclaim\Administrator\Helper;

// phpcs:disable PSR1.Files.SideEffects
\defined('_JEXEC') or die;
// phpcs:enable PSR1.Files.SideEffects

use Joomla\CMS\Application\ApplicationHelper;
use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Image\Image;
use Joomla\Filesystem\Folder;
use Joomla\Filesystem\Path;

/**
 * Image Migration Helper - Migrate existing images to new folder structure
 *
 * @package  Proclaim.Admin
 * @since    10.2.0
 */
class CwmImageMigration
{
    /**
     * Core image directory (relative to JPATH_ROOT on a Joomla site).
     * All files shipped with the component live here; Image Tools must skip them.
     */
    private const string CORE_IMAGE_DIR = 'media/com_proclaim/images';

    /**
     * Per-type configuration for thumbnail/WebP regeneration.
     *
     * @since 10.1.0
     */
    private const array REGEN_TYPE_CONFIG = [
        'studies' => [
            'table'       => '#__bsms_studies',
            'imageCol'    => 'image',
            'thumbCol'    => 'thumbnailm',
            'sizeParam'   => 'thumbnail_study_size',
            'sizeDefault' => 600,
        ],
        'teachers' => [
            'table'         => '#__bsms_teachers',
            'imageCol'      => 'image',
            'thumbCol'      => 'teacher_thumbnail',
            'extraImageCol' => 'teacher_image',
            'sizeParam'     => 'thumbnail_teacher_size',
            'sizeDefault'   => 300,
        ],
        'series' => [
            'table'       => '#__bsms_series',
            'imageCol'    => 'image',
            'thumbCol'    => 'series_thumbnail',
            'sizeParam'   => 'thumbnail_series_size',
            'sizeDefault' => 300,
        ],
    ];

    /**
     * Determine whether a path points to a core component image
     *
     * Core images are shipped with the component in media/com_proclaim/images/.
     * They must never be migrated, deleted, or regenerated by Image Tools.
     *
     * Handles three path formats:
     *  - Full path:    media/com_proclaim/images/speaker24.png
     *  - Legacy path:  images/biblestudy/speaker24.png  (old BibleStudy location)
     *  - Bare filename: speaker24.png
     *
     * @param   string  $path  Image path (relative to JPATH_ROOT or bare filename)
     *
     * @return  bool
     *
     * @since 10.1.0
     */
    public static function isCoreImage(string $path): bool
    {
        $path = ltrim($path, '/');

        if ($path === '') {
            return false;
        }

        // Direct path to core images directory
        if (str_starts_with($path, self::CORE_IMAGE_DIR . '/')) {
            return true;
        }

        // Legacy path: images/biblestudy/<filename> with no deeper subdirectory
        // (structured user paths look like images/biblestudy/studies/alias-123/file.jpg)
        if (
            str_starts_with($path, 'images/biblestudy/')
            && !str_contains(substr($path, 18), '/')
            && is_file(JPATH_ROOT . '/' . self::CORE_IMAGE_DIR . '/' . basename($path))
        ) {
            return true;
        }

        // Bare filename that exists in the core images directory
        if (
            !str_contains($path, '/')
            && is_file(JPATH_ROOT . '/' . self::CORE_IMAGE_DIR . '/' . $path)
        ) {
            return true;
        }

        return false;
    }

    /**
     * Get records needing migration for a specific type
     *
     * @param   string  $type  Record type: 'studies', 'teachers', or 'series'
     *
     * @return  array  Records with images not in the new folder structure
     *
     * @since 10.2.0
     */
    public static function getRecordsNeedingMigration(string $type): array
    {
        $db    = Factory::getContainer()->get('DatabaseDriver');
        $query = $db->getQuery(true);

        // SQL exclusion for core component images
        $coreExclude = ' NOT LIKE ' . $db->q('media/com_proclaim/images/%');

        switch ($type) {
            case 'studies':
                $col = $db->quoteName('thumbnailm');
                $query->select(
                    $db->quoteName('id') . ', ' . $db->quoteName('studytitle') . ', ' . $db->quoteName('alias') . ', '
                    . $db->quoteName('thumbnailm', 'image_path') . ', ' . $db->quoteName('image', 'original_path')
                )
                    ->from($db->quoteName('#__bsms_studies'))
                    ->where($col . ' IS NOT NULL')
                    ->where($col . ' != ' . $db->q(''))
                    ->where('LENGTH(' . $col . ') > 1')
                    ->where($col . ' NOT LIKE ' . $db->q('images/biblestudy/studies/%-%/%'))
                    ->where($col . $coreExclude);
                break;

            case 'teachers':
                $col = $db->quoteName('teacher_thumbnail');
                $query->select(
                    $db->quoteName('id') . ', ' . $db->quoteName('teachername') . ', ' . $db->quoteName('alias') . ', '
                    . $db->quoteName('teacher_thumbnail', 'image_path') . ', '
                    . 'COALESCE(' . $db->quoteName('teacher_image') . ', ' . $db->quoteName('image') . ') AS '
                    . $db->quoteName('original_path')
                )
                    ->from($db->quoteName('#__bsms_teachers'))
                    ->where($col . ' IS NOT NULL')
                    ->where($col . ' != ' . $db->q(''))
                    ->where('LENGTH(' . $col . ') > 1')
                    ->where($col . ' NOT LIKE ' . $db->q('images/biblestudy/teachers/%-%/%'))
                    ->where($col . $coreExclude);
                break;

            case 'series':
                $col = $db->quoteName('series_thumbnail');
                $query->select(
                    $db->quoteName('id') . ', ' . $db->quoteName('series_text', 'title') . ', ' . $db->quoteName('alias') . ', '
                    . $db->quoteName('series_thumbnail', 'image_path') . ', ' . $db->quoteName('image', 'original_path')
                )
                    ->from($db->quoteName('#__bsms_series'))
                    ->where($col . ' IS NOT NULL')
                    ->where($col . ' != ' . $db->q(''))
                    ->where('LENGTH(' . $col . ') > 1')
                    ->where($col . ' NOT LIKE ' . $db->q('images/biblestudy/series/%-%/%'))
                    ->where($col . $coreExclude);
                break;

            default:
                return [];
        }

        $db->setQuery($query);
        $rows = $db->loadObjectList() ?: [];

        // PHP-level filter for bare filenames and legacy paths that resolve to core images
        return array_values(array_filter(
            $rows,
            fn ($row) => !self::isCoreImage($row->image_path)
        ));
    }

    /**
     * Get migration counts for all types
     *
     * @return  array{studies: int, teachers: int, series: int, total: int}
     *
     * @since 10.2.0
     */
    public static function getMigrationCounts(): array
    {
        $counts = [
            'studies'  => \count(self::getRecordsNeedingMigration('studies')),
            'teachers' => \count(self::getRecordsNeedingMigration('teachers')),
            'series'   => \count(self::getRecordsNeedingMigration('series')),
        ];

        $counts['total'] = $counts['studies'] + $counts['teachers'] + $counts['series'];

        return $counts;
    }

    /**
     * Look up a record from the DB and migrate its images
     *
     * @param   string  $type  Record type: 'studies', 'teachers', or 'series'
     * @param   int     $id    Record ID
     *
     * @return  array{success: bool, newPath: ?string, error: ?string}
     *
     * @since 10.2.0
     */
    public static function migrateRecordById(string $type, int $id): array
    {
        $db    = Factory::getContainer()->get('DatabaseDriver');
        $query = $db->getQuery(true);

        switch ($type) {
            case 'studies':
                $query->select($db->quoteName(['studytitle', 'alias', 'thumbnailm', 'image']))
                    ->from($db->quoteName('#__bsms_studies'))
                    ->where($db->quoteName('id') . ' = ' . (int) $id);
                break;

            case 'teachers':
                $query->select($db->quoteName(['teachername', 'alias', 'teacher_thumbnail', 'teacher_image', 'image']))
                    ->from($db->quoteName('#__bsms_teachers'))
                    ->where($db->quoteName('id') . ' = ' . (int) $id);
                break;

            case 'series':
                $query->select($db->quoteName(['series_text', 'alias', 'series_thumbnail', 'image']))
                    ->from($db->quoteName('#__bsms_series'))
                    ->where($db->quoteName('id') . ' = ' . (int) $id);
                break;

            default:
                return ['success' => false, 'newPath' => null, 'error' => 'Invalid type: ' . $type];
        }

        $db->setQuery($query);
        $row = $db->loadObject();

        if (!$row) {
            return ['success' => false, 'newPath' => null, 'error' => 'Record not found: ' . $type . ' #' . $id];
        }

        // Extract title and image path from the row
        $title   = $row->studytitle ?? $row->teachername ?? $row->series_text ?? '';
        $oldPath = trim($row->thumbnailm ?? $row->teacher_thumbnail ?? $row->series_thumbnail ?? '');

        // Check if the alias-ID folder already has migrated files (previous run
        // may have copied files but failed to update DB columns)
        $existing = self::findExistingMigratedFiles($type, $id, $title, $row->alias ?? '');

        if ($existing !== null) {
            return self::updateDbFromExistingFiles($type, $id, $existing);
        }

        // Prefer the image column (original full-size) over thumbnail when available
        $imagePath = trim($row->image ?? $row->teacher_image ?? '');

        if ($imagePath !== '' && \strlen($imagePath) > 1 && !self::isCoreImage($imagePath)) {
            $imageAbsPath = Path::clean(JPATH_ROOT . '/' . $imagePath);

            if (is_file($imageAbsPath)) {
                $oldPath = $imagePath;
            }
        }

        // Treat '0', single-char junk, and empty as "no image" — skip (not migratable)
        if ($oldPath === '' || \strlen($oldPath) <= 1) {
            return ['success' => false, 'newPath' => null, 'error' => 'No valid image path for ' . $type . ' #' . $id, 'junk' => true];
        }

        // Skip core component images — they live in media/com_proclaim/images/
        if (self::isCoreImage($oldPath)) {
            return ['success' => false, 'newPath' => null, 'error' => 'Core image (skipped): ' . $oldPath, 'core' => true];
        }

        return self::migrateRecord($type, $id, $title, $oldPath);
    }

    /**
     * Migrate a single record's images to the new folder structure
     *
     * @param   string  $type       Record type: 'studies', 'teachers', or 'series'
     * @param   int     $id         Record ID
     * @param   string  $title      Record title for folder naming
     * @param   string  $oldPath    Current image path
     * @param   int     $thumbSize  Thumbnail size (default: 300)
     *
     * @return  array{success: bool, newPath: ?string, error: ?string}
     *
     * @since 10.2.0
     */
    public static function migrateRecord(
        string $type,
        int $id,
        string $title,
        string $oldPath,
        int $thumbSize = 300
    ): array {
        // Build the new folder path with title-ID format
        $alias     = ApplicationHelper::stringURLSafe($title ?: $type);
        $newFolder = 'images/biblestudy/' . $type . '/' . $alias . '-' . $id;

        // Clean Joomla media field metadata (#joomlaImage://...)
        $cleanImage = HTMLHelper::_('cleanImageURL', $oldPath);
        $cleanPath  = $cleanImage->url;

        // Handle bare filenames (no directory separator) by prepending configured image folder
        if (!str_contains($cleanPath, '/')) {
            $folderKeys = [
                'studies'  => 'image_folder',
                'teachers' => 'teacher_image_folder',
                'series'   => 'series_image_folder',
            ];
            $folderKey   = $folderKeys[$type] ?? 'image_folder';
            $imageFolder = Cwmparams::getAdmin()->params->get($folderKey, 'images');
            $cleanPath   = $imageFolder . '/' . $cleanPath;
        }

        // Find the original image (not the thumbnail)
        $oldAbsPath = Path::clean(JPATH_ROOT . '/' . $cleanPath);

        // If this is a thumbnail path, try to find the original full-size image first
        $sourceImage = $cleanPath;
        $sourceFound = true;
        $relocated   = false;
        $foundAt     = null;
        $basename    = basename($cleanPath);

        if (str_contains($basename, 'thumb_')) {
            // Try the exact extension first, then alternate extensions
            $strippedBase  = str_replace('thumb_', '', $basename);
            $strippedName  = pathinfo($strippedBase, PATHINFO_FILENAME);
            $dirName       = \dirname($cleanPath);
            $foundOriginal = false;

            // Try original name as-is, then alternate extensions (thumb may be .jpg but original .png)
            foreach ([$strippedBase, ...array_map(
                fn ($ext) => $strippedName . '.' . $ext,
                ['jpg', 'jpeg', 'png', 'webp', 'gif']
            )] as $candidateName) {
                $possibleOriginal = $dirName . '/' . $candidateName;
                $possibleAbsPath  = Path::clean(JPATH_ROOT . '/' . $possibleOriginal);

                if (is_file($possibleAbsPath)) {
                    $sourceImage   = $possibleOriginal;
                    $foundOriginal = true;
                    break;
                }
            }

            if (!$foundOriginal) {
                if (is_file($oldAbsPath)) {
                    // Thumbnail exists, use it as source
                    $sourceImage = $cleanPath;
                } else {
                    $sourceFound = false;
                }
            }
        } elseif (!is_file($oldAbsPath)) {
            $sourceFound = false;
        }

        // Fallback: search the images directory tree for a matching filename
        if (!$sourceFound) {
            $searchName = str_contains($basename, 'thumb_')
                ? str_replace('thumb_', '', $basename)
                : $basename;

            $found = self::findImageFile($searchName, $type);

            // If original not found but this is a thumb_ path, also try the thumbnail filename
            if ($found === null && str_contains($basename, 'thumb_')) {
                $found = self::findImageFile($basename, $type);
            }

            if ($found !== null) {
                $sourceImage = $found;
                $sourceFound = true;
                $relocated   = true;
                $foundAt     = $found;
            }
        }

        // If source file is still missing, report it but do NOT clear the DB field.
        // The admin can clear unresolvable records manually via the dedicated button.
        if (!$sourceFound) {
            return [
                'success'      => false,
                'newPath'      => null,
                'error'        => 'Source file not found',
                'missingPath'  => $cleanPath,
                'absolutePath' => $oldAbsPath,
            ];
        }

        // Create new thumbnail using Cwmthumbnail
        try {
            $result = Cwmthumbnail::create($sourceImage, $newFolder, $thumbSize, $title);
        } catch (\Throwable $e) {
            return [
                'success'     => false,
                'newPath'     => null,
                'error'       => 'Thumbnail error: ' . $e->getMessage(),
                'missingPath' => $cleanPath,
            ];
        }

        if ($result === false) {
            return [
                'success'     => false,
                'newPath'     => null,
                'error'       => 'Failed to create thumbnail (file copy or GD init failed)',
                'missingPath' => $cleanPath,
            ];
        }

        // Update database
        $db    = Factory::getContainer()->get('DatabaseDriver');
        $query = $db->getQuery(true);

        switch ($type) {
            case 'studies':
                $query->update($db->quoteName('#__bsms_studies'))
                    ->set($db->quoteName('thumbnailm') . ' = ' . $db->q($result['thumbnail']))
                    ->set($db->quoteName('image') . ' = ' . $db->q($result['image']))
                    ->where($db->quoteName('id') . ' = ' . (int) $id);
                break;

            case 'teachers':
                $query->update($db->quoteName('#__bsms_teachers'))
                    ->set($db->quoteName('teacher_thumbnail') . ' = ' . $db->q($result['thumbnail']))
                    ->set($db->quoteName('teacher_image') . ' = ' . $db->q($result['image']))
                    ->set($db->quoteName('image') . ' = ' . $db->q($result['image']))
                    ->where($db->quoteName('id') . ' = ' . (int) $id);
                break;

            case 'series':
                $query->update($db->quoteName('#__bsms_series'))
                    ->set($db->quoteName('series_thumbnail') . ' = ' . $db->q($result['thumbnail']))
                    ->set($db->quoteName('image') . ' = ' . $db->q($result['image']))
                    ->where($db->quoteName('id') . ' = ' . (int) $id);
                break;
        }

        $db->setQuery($query);
        $db->execute();

        $response = ['success' => true, 'newPath' => $result['thumbnail'], 'error' => null];

        if ($relocated) {
            $response['relocated']    = true;
            $response['originalPath'] = $cleanPath;
            $response['foundAt']      = $foundAt;
        }

        return $response;
    }

    /**
     * Check if an alias-ID folder already contains migrated files for a record
     *
     * A previous migration run may have copied files to the proper folder but
     * failed to update the DB columns. This detects that case so we can fix
     * the DB without re-copying files.
     *
     * @param   string  $type   Record type: 'studies', 'teachers', or 'series'
     * @param   int     $id     Record ID
     * @param   string  $title  Record title (used to build folder name)
     * @param   string  $alias  Record alias (preferred over title for folder name)
     *
     * @return  ?array{image: string, thumbnail: string}  Relative paths if found, null otherwise
     *
     * @since 10.1.0
     */
    private static function findExistingMigratedFiles(string $type, int $id, string $title, string $alias): ?array
    {
        // Build the expected alias-ID folder name
        $folderAlias = $alias ?: ApplicationHelper::stringURLSafe($title ?: $type);
        $expectedDir = JPATH_ROOT . '/images/biblestudy/' . $type . '/' . $folderAlias . '-' . $id;

        // Also check bare-ID folder (legacy migration artefact: folder named just "528" instead of "alias-528")
        $bareIdDir = JPATH_ROOT . '/images/biblestudy/' . $type . '/' . $id;

        $dirsToCheck = [];

        if (is_dir($expectedDir)) {
            $dirsToCheck[] = ['dir' => $expectedDir, 'relDir' => 'images/biblestudy/' . $type . '/' . $folderAlias . '-' . $id];
        }

        if (is_dir($bareIdDir)) {
            $dirsToCheck[] = ['dir' => $bareIdDir, 'relDir' => 'images/biblestudy/' . $type . '/' . $id];
        }

        if (empty($dirsToCheck)) {
            return null;
        }

        $imageExts = ['jpg', 'jpeg', 'png', 'webp', 'gif'];

        foreach ($dirsToCheck as $candidate) {
            $thumbFile = null;
            $imageFile = null;

            $files = @scandir($candidate['dir']);

            if ($files === false) {
                continue;
            }

            foreach ($files as $file) {
                if ($file === '.' || $file === '..') {
                    continue;
                }

                $ext = strtolower(pathinfo($file, PATHINFO_EXTENSION));

                if (!\in_array($ext, $imageExts, true)) {
                    continue;
                }

                if (str_starts_with($file, 'thumb_') && $ext !== 'webp') {
                    $thumbFile = $file;
                } elseif (!str_starts_with($file, 'thumb_') && $ext !== 'webp') {
                    $imageFile = $file;
                }
            }

            if ($thumbFile !== null || $imageFile !== null) {
                return [
                    'image'     => $imageFile ? $candidate['relDir'] . '/' . $imageFile : '',
                    'thumbnail' => $thumbFile ? $candidate['relDir'] . '/' . $thumbFile : '',
                ];
            }
        }

        return null;
    }

    /**
     * Update DB columns from already-migrated files in the alias-ID folder
     *
     * @param   string  $type      Record type: 'studies', 'teachers', or 'series'
     * @param   int     $id        Record ID
     * @param   array   $existing  Array with 'image' and 'thumbnail' relative paths
     *
     * @return  array{success: bool, newPath: ?string, error: ?string}
     *
     * @since 10.1.0
     */
    private static function updateDbFromExistingFiles(string $type, int $id, array $existing): array
    {
        $db    = Factory::getContainer()->get('DatabaseDriver');
        $query = $db->getQuery(true);

        $thumbPath = $existing['thumbnail'];
        $imagePath = $existing['image'];

        switch ($type) {
            case 'studies':
                $query->update($db->quoteName('#__bsms_studies'))
                    ->set($db->quoteName('thumbnailm') . ' = ' . $db->q($thumbPath))
                    ->set($db->quoteName('image') . ' = ' . $db->q($imagePath))
                    ->where($db->quoteName('id') . ' = ' . (int) $id);
                break;

            case 'teachers':
                $query->update($db->quoteName('#__bsms_teachers'))
                    ->set($db->quoteName('teacher_thumbnail') . ' = ' . $db->q($thumbPath))
                    ->set($db->quoteName('teacher_image') . ' = ' . $db->q($imagePath))
                    ->set($db->quoteName('image') . ' = ' . $db->q($imagePath))
                    ->where($db->quoteName('id') . ' = ' . (int) $id);
                break;

            case 'series':
                $query->update($db->quoteName('#__bsms_series'))
                    ->set($db->quoteName('series_thumbnail') . ' = ' . $db->q($thumbPath))
                    ->set($db->quoteName('image') . ' = ' . $db->q($imagePath))
                    ->where($db->quoteName('id') . ' = ' . (int) $id);
                break;
        }

        $db->setQuery($query);
        $db->execute();

        return [
            'success'  => true,
            'newPath'  => $thumbPath,
            'error'    => null,
            'relinked' => true,
        ];
    }

    /**
     * Get a batch of records to migrate
     *
     * @param   string  $type        Record type
     * @param   int     $limit       Maximum number of records to return
     * @param   int[]   $excludeIds  Record IDs to skip (already failed)
     *
     * @return  array{records: array, remaining: int}
     *
     * @since 10.2.0
     */
    public static function getBatch(string $type, int $limit = 10, array $excludeIds = []): array
    {
        $records = self::getRecordsNeedingMigration($type);

        // Filter out records that already failed — they stay in the DB
        // but the JS tracks them and sends their IDs to skip
        if (!empty($excludeIds)) {
            $records = array_values(array_filter(
                $records,
                fn ($r) => !\in_array((int) $r->id, $excludeIds, true)
            ));
        }

        $batch     = \array_slice($records, 0, $limit);
        $remaining = \count($records) - \count($batch);

        return [
            'records'   => $batch,
            'remaining' => $remaining,
        ];
    }

    /**
     * Clear the image field for a record so it won't be returned by getRecordsNeedingMigration()
     *
     * Called when the source file is missing — the image is gone, nothing to migrate.
     * Logs the cleared value to a CSV file so admins can search for the file manually.
     *
     * @param   string  $type     Record type: 'studies', 'teachers', or 'series'
     * @param   int     $id       Record ID
     * @param   string  $oldPath  The image path being cleared (for the log)
     * @param   string  $title    Record title (for the log)
     *
     * @return  void
     *
     * @since 10.2.0
     */
    private static function clearImageField(string $type, int $id, string $oldPath = '', string $title = ''): void
    {
        // Log the cleared value before wiping it
        self::logClearedImage($type, $id, $oldPath, $title);

        $db    = Factory::getContainer()->get('DatabaseDriver');
        $query = $db->getQuery(true);

        switch ($type) {
            case 'studies':
                $query->update($db->quoteName('#__bsms_studies'))
                    ->set($db->quoteName('thumbnailm') . ' = ' . $db->q(''))
                    ->where($db->quoteName('id') . ' = ' . (int) $id);
                break;

            case 'teachers':
                $query->update($db->quoteName('#__bsms_teachers'))
                    ->set($db->quoteName('teacher_thumbnail') . ' = ' . $db->q(''))
                    ->where($db->quoteName('id') . ' = ' . (int) $id);
                break;

            case 'series':
                $query->update($db->quoteName('#__bsms_series'))
                    ->set($db->quoteName('series_thumbnail') . ' = ' . $db->q(''))
                    ->set($db->quoteName('image') . ' = ' . $db->q(''))
                    ->where($db->quoteName('id') . ' = ' . (int) $id);
                break;
        }

        $db->setQuery($query);
        $db->execute();
    }

    /**
     * Log a cleared image value to CSV for administrator review
     *
     * Writes to administrator/logs/proclaim_cleared_images.csv so admins
     * can search other locations for the missing files.
     *
     * @param   string  $type     Record type
     * @param   int     $id       Record ID
     * @param   string  $oldPath  The image path that was cleared
     * @param   string  $title    Record title for identification
     *
     * @return  void
     *
     * @since 10.2.0
     */
    private static function logClearedImage(string $type, int $id, string $oldPath, string $title): void
    {
        $logFile = JPATH_ADMINISTRATOR . '/logs/proclaim_cleared_images.csv';

        // Write header row if this is a new file
        if (!is_file($logFile)) {
            file_put_contents($logFile, "Date,Type,ID,Title,Cleared Path\n");
        }

        $row = [
            date('Y-m-d H:i:s'),
            $type,
            (string) $id,
            str_replace(['"', "\n", "\r"], ['""', ' ', ' '], $title),
            str_replace('"', '""', $oldPath),
        ];

        file_put_contents($logFile, '"' . implode('","', $row) . "\"\n", FILE_APPEND);
    }

    /**
     * Get the path to the cleared images log file
     *
     * @return  string  Absolute path to the CSV log
     *
     * @since 10.2.0
     */
    public static function getClearedLogPath(): string
    {
        return JPATH_ADMINISTRATOR . '/logs/proclaim_cleared_images.csv';
    }

    /**
     * Find all records with image paths that cannot be resolved to real files
     *
     * Checks each record returned by getRecordsNeedingMigration() to see if
     * the source file actually exists on disk. Returns those that don't.
     *
     * @return  array{records: list<array{type: string, id: int, title: string, path: string}>, count: int}
     *
     * @since 10.2.0
     */
    public static function getUnresolvableRecords(): array
    {
        $unresolvable = [];

        foreach (['studies', 'teachers', 'series'] as $type) {
            $records = self::getRecordsNeedingMigration($type);

            foreach ($records as $row) {
                $imagePath = trim($row->image_path ?? '');
                $title     = $row->studytitle ?? $row->teachername ?? $row->title ?? '';
                $alias     = $row->alias ?? '';

                // Check if alias-ID folder already has migrated files (DB wasn't updated)
                $existing = self::findExistingMigratedFiles($type, (int) $row->id, $title, $alias);

                if ($existing !== null) {
                    continue;
                }

                // Junk values are always unresolvable
                if ($imagePath === '' || \strlen($imagePath) <= 1) {
                    $unresolvable[] = ['type' => $type, 'id' => (int) $row->id, 'title' => $title, 'path' => $imagePath];

                    continue;
                }

                // Quick check: if the image column has a valid file, record is resolvable
                $originalPath = trim($row->original_path ?? '');

                if ($originalPath !== '' && \strlen($originalPath) > 1) {
                    $origAbsPath = Path::clean(JPATH_ROOT . '/' . $originalPath);

                    if (is_file($origAbsPath)) {
                        continue;
                    }
                }

                // Clean Joomla media field metadata
                $cleanImage = HTMLHelper::_('cleanImageURL', $imagePath);
                $cleanPath  = $cleanImage->url;

                // Handle bare filenames
                if (!str_contains($cleanPath, '/')) {
                    $folderKeys = [
                        'studies'  => 'image_folder',
                        'teachers' => 'teacher_image_folder',
                        'series'   => 'series_image_folder',
                    ];
                    $folderKey   = $folderKeys[$type] ?? 'image_folder';
                    $imageFolder = Cwmparams::getAdmin()->params->get($folderKey, 'images');
                    $cleanPath   = $imageFolder . '/' . $cleanPath;
                }

                $absPath  = Path::clean(JPATH_ROOT . '/' . $cleanPath);
                $basename = basename($cleanPath);

                // Check if original or thumbnail exists
                $found = false;

                if (str_contains($basename, 'thumb_')) {
                    // Check for original with exact extension and alternate extensions
                    $strippedBase = str_replace('thumb_', '', $basename);
                    $strippedName = pathinfo($strippedBase, PATHINFO_FILENAME);
                    $dirName      = \dirname($cleanPath);

                    foreach ([$strippedBase, ...array_map(
                        fn ($ext) => $strippedName . '.' . $ext,
                        ['jpg', 'jpeg', 'png', 'webp', 'gif']
                    )] as $candidateName) {
                        $possibleOriginal = $dirName . '/' . $candidateName;

                        if (is_file(Path::clean(JPATH_ROOT . '/' . $possibleOriginal))) {
                            $found = true;
                            break;
                        }
                    }

                    // Also check if the thumbnail itself exists
                    if (!$found && is_file($absPath)) {
                        $found = true;
                    }
                } elseif (is_file($absPath)) {
                    $found = true;
                }

                // Fallback: search image directories
                if (!$found) {
                    $searchName = str_contains($basename, 'thumb_')
                        ? str_replace('thumb_', '', $basename)
                        : $basename;
                    $found = self::findImageFile($searchName, $type) !== null;

                    // Also try the thumbnail filename itself
                    if (!$found && str_contains($basename, 'thumb_')) {
                        $found = self::findImageFile($basename, $type) !== null;
                    }
                }

                if (!$found) {
                    $title          = $row->studytitle ?? $row->teachername ?? $row->title ?? '';
                    $unresolvable[] = ['type' => $type, 'id' => (int) $row->id, 'title' => $title, 'path' => $cleanPath];
                }
            }
        }

        return ['records' => $unresolvable, 'count' => \count($unresolvable)];
    }

    /**
     * Clear all unresolvable image fields from the database
     *
     * For each record whose image file cannot be found, clears the DB field
     * and logs the old value to CSV. This is a manual opt-in operation — the
     * admin must explicitly trigger it after reviewing the missing files.
     *
     * @return  array{cleared: int, logFile: string}
     *
     * @since 10.2.0
     */
    public static function clearUnresolvableImages(): array
    {
        $result  = self::getUnresolvableRecords();
        $cleared = 0;

        foreach ($result['records'] as $record) {
            self::clearImageField($record['type'], $record['id'], $record['path'], $record['title']);
            $cleared++;
        }

        return ['cleared' => $cleared, 'logFile' => self::getClearedLogPath()];
    }

    /**
     * Count bare-ID folders per type that can be recovered
     *
     * Scans images/biblestudy/{type}/ for numeric-only subdirectories
     * where the DB record has empty image fields but the folder has files.
     *
     * @return  array{studies: int, teachers: int, series: int, total: int}
     *
     * @since 10.1.0
     */
    public static function getRecoveryCounts(): array
    {
        $db     = Factory::getContainer()->get('DatabaseDriver');
        $counts = ['studies' => 0, 'teachers' => 0, 'series' => 0];

        foreach (array_keys(self::REGEN_TYPE_CONFIG) as $type) {
            $baseDir = JPATH_ROOT . '/images/biblestudy/' . $type;

            if (!is_dir($baseDir)) {
                continue;
            }

            $subDirs = @scandir($baseDir);

            if ($subDirs === false) {
                continue;
            }

            // Load valid IDs for this type so we only count recoverable folders
            $table = self::REGEN_TYPE_CONFIG[$type]['table'];
            $query = $db->getQuery(true)
                ->select($db->quoteName('id'))
                ->from($db->quoteName($table));
            $db->setQuery($query);
            $validIds = array_map('intval', $db->loadColumn() ?: []);

            foreach ($subDirs as $dirName) {
                if ($dirName === '.' || $dirName === '..' || !ctype_digit($dirName)) {
                    continue;
                }

                $absDir = $baseDir . '/' . $dirName;

                if (!is_dir($absDir)) {
                    continue;
                }

                // Only count if the DB record exists (otherwise it's an orphan, not recoverable)
                if (!\in_array((int) $dirName, $validIds, true)) {
                    continue;
                }

                // Check if the folder has any image files
                if (self::dirHasImageFiles($absDir)) {
                    $counts[$type]++;
                }
            }
        }

        $counts['total'] = $counts['studies'] + $counts['teachers'] + $counts['series'];

        return $counts;
    }

    /**
     * Recover bare-ID folders by migrating their images to proper alias-ID folders
     *
     * For each numeric-only folder, looks up the DB record, generates proper
     * thumbnails in the alias-ID folder, updates DB columns, and removes
     * the old bare-ID folder if it becomes empty.
     *
     * @param   string  $type   Record type: 'studies', 'teachers', or 'series'
     * @param   int     $limit  Maximum folders to process per batch
     *
     * @return  array{recovered: int, skipped: int, errors: int, remaining: int, errorDetails: list<string>}
     *
     * @since 10.1.0
     */
    public static function recoverBareIdFolders(string $type, int $limit = 10): array
    {
        $cfg    = self::REGEN_TYPE_CONFIG[$type] ?? null;
        $result = [
            'recovered'    => 0,
            'skipped'      => 0,
            'errors'       => 0,
            'remaining'    => 0,
            'errorDetails' => [],
        ];

        if ($cfg === null) {
            $result['errorDetails'][] = 'Invalid type: ' . $type;

            return $result;
        }

        $baseDir = JPATH_ROOT . '/images/biblestudy/' . $type;

        if (!is_dir($baseDir)) {
            return $result;
        }

        $subDirs = @scandir($baseDir);

        if ($subDirs === false) {
            return $result;
        }

        $db        = Factory::getContainer()->get('DatabaseDriver');
        $params    = Cwmparams::getAdmin()->params;
        $thumbSize = (int) $params->get($cfg['sizeParam'], $cfg['sizeDefault']);
        $processed = 0;

        foreach ($subDirs as $dirName) {
            if ($dirName === '.' || $dirName === '..' || !ctype_digit($dirName)) {
                continue;
            }

            $absDir = $baseDir . '/' . $dirName;

            if (!is_dir($absDir)) {
                continue;
            }

            if (!self::dirHasImageFiles($absDir)) {
                continue;
            }

            if ($processed >= $limit) {
                $result['remaining']++;

                continue;
            }

            $processed++;
            $id = (int) $dirName;

            // Look up the DB record
            $query = $db->getQuery(true);

            // Only select the columns needed for folder naming — the source
            // image comes from the filesystem, not the DB.
            switch ($type) {
                case 'studies':
                    $query->select($db->quoteName(['id', 'studytitle', 'alias']))
                        ->from($db->quoteName('#__bsms_studies'))
                        ->where($db->quoteName('id') . ' = ' . $id);
                    break;

                case 'teachers':
                    $query->select($db->quoteName(['id', 'teachername', 'alias']))
                        ->from($db->quoteName('#__bsms_teachers'))
                        ->where($db->quoteName('id') . ' = ' . $id);
                    break;

                case 'series':
                    $query->select($db->quoteName(['id', 'series_text', 'alias']))
                        ->from($db->quoteName('#__bsms_series'))
                        ->where($db->quoteName('id') . ' = ' . $id);
                    break;
            }

            $db->setQuery($query);
            $row = $db->loadObject();

            if (!$row) {
                $result['skipped']++;

                continue;
            }

            $title       = $row->studytitle ?? $row->teachername ?? $row->series_text ?? '';
            $alias       = $row->alias ?? '';
            $folderAlias = $alias ?: ApplicationHelper::stringURLSafe($title ?: $type);
            $newFolder   = 'images/biblestudy/' . $type . '/' . $folderAlias . '-' . $id;

            // If the alias-ID folder already has properly migrated files,
            // just clean up the bare-ID folder — no need to re-migrate.
            // Note: we check only the alias-ID folder directly (not via
            // findExistingMigratedFiles which also checks the bare-ID folder
            // we're trying to clean up).
            $aliasIdDir = JPATH_ROOT . '/' . $newFolder;

            if (is_dir($aliasIdDir) && self::dirHasImageFiles($aliasIdDir)) {
                self::cleanupBareIdFolder($absDir);

                // Only count as recovered if the bare-ID folder was actually removed.
                // If cleanup failed (e.g. permissions), skip it to avoid an infinite
                // loop where the same folder is "recovered" every batch.
                if (!is_dir($absDir) || !self::dirHasImageFiles($absDir)) {
                    $result['recovered']++;
                } else {
                    $result['skipped']++;
                }

                continue;
            }

            // Find the best source image in the bare-ID folder
            $sourceFile = self::findBestImageInDir($absDir);

            if ($sourceFile === null) {
                $result['skipped']++;

                continue;
            }

            $sourceRel = self::makeRelative($sourceFile);

            try {
                $thumbResult = Cwmthumbnail::create($sourceRel, $newFolder, $thumbSize, $title);
            } catch (\Throwable $e) {
                $result['errors']++;
                $result['errorDetails'][] = $type . ' #' . $id . ': ' . $e->getMessage();

                continue;
            }

            if ($thumbResult === false) {
                $result['errors']++;
                $result['errorDetails'][] = $type . ' #' . $id . ': Thumbnail creation failed';

                continue;
            }

            // Update DB columns
            $update = $db->getQuery(true);

            switch ($type) {
                case 'studies':
                    $update->update($db->quoteName('#__bsms_studies'))
                        ->set($db->quoteName('thumbnailm') . ' = ' . $db->q($thumbResult['thumbnail']))
                        ->set($db->quoteName('image') . ' = ' . $db->q($thumbResult['image']))
                        ->where($db->quoteName('id') . ' = ' . $id);
                    break;

                case 'teachers':
                    $update->update($db->quoteName('#__bsms_teachers'))
                        ->set($db->quoteName('teacher_thumbnail') . ' = ' . $db->q($thumbResult['thumbnail']))
                        ->set($db->quoteName('teacher_image') . ' = ' . $db->q($thumbResult['image']))
                        ->set($db->quoteName('image') . ' = ' . $db->q($thumbResult['image']))
                        ->where($db->quoteName('id') . ' = ' . $id);
                    break;

                case 'series':
                    $update->update($db->quoteName('#__bsms_series'))
                        ->set($db->quoteName('series_thumbnail') . ' = ' . $db->q($thumbResult['thumbnail']))
                        ->set($db->quoteName('image') . ' = ' . $db->q($thumbResult['image']))
                        ->where($db->quoteName('id') . ' = ' . $id);
                    break;
            }

            $db->setQuery($update);
            $db->execute();

            // Clean up the old bare-ID folder
            self::cleanupBareIdFolder($absDir);

            // Only count as recovered if cleanup actually removed the folder
            if (!is_dir($absDir) || !self::dirHasImageFiles($absDir)) {
                $result['recovered']++;
            } else {
                $result['skipped']++;
            }
        }

        return $result;
    }

    /**
     * Check whether a directory contains any image files
     *
     * @param   string  $absDir  Absolute directory path
     *
     * @return  bool
     *
     * @since 10.1.0
     */
    private static function dirHasImageFiles(string $absDir): bool
    {
        $imageExts = ['jpg', 'jpeg', 'png', 'webp', 'gif'];
        $files     = @scandir($absDir);

        if ($files === false) {
            return false;
        }

        foreach ($files as $file) {
            if ($file === '.' || $file === '..') {
                continue;
            }

            $ext = strtolower(pathinfo($file, PATHINFO_EXTENSION));

            if (\in_array($ext, $imageExts, true)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Find the best source image file in a directory
     *
     * Prefers non-thumb originals over thumbnails. Returns the absolute path.
     *
     * @param   string  $absDir  Absolute directory path
     *
     * @return  ?string  Absolute path to best image file, or null
     *
     * @since 10.1.0
     */
    private static function findBestImageInDir(string $absDir): ?string
    {
        $preferredExts = ['jpg', 'jpeg', 'png', 'gif'];
        $allExts       = ['jpg', 'jpeg', 'png', 'gif', 'webp'];
        $files         = @scandir($absDir);

        if ($files === false) {
            return null;
        }

        $original     = null;
        $thumbnail    = null;
        $webpOriginal = null;
        $webpThumb    = null;

        foreach ($files as $file) {
            if ($file === '.' || $file === '..') {
                continue;
            }

            $ext = strtolower(pathinfo($file, PATHINFO_EXTENSION));

            if (!\in_array($ext, $allExts, true)) {
                continue;
            }

            $isThumb = str_starts_with($file, 'thumb_');
            $isWebp  = $ext === 'webp';

            if ($isThumb) {
                if ($isWebp) {
                    $webpThumb = $absDir . '/' . $file;
                } else {
                    $thumbnail = $absDir . '/' . $file;
                }
            } else {
                if ($isWebp) {
                    $webpOriginal = $absDir . '/' . $file;
                } else {
                    $original = $absDir . '/' . $file;
                }
            }
        }

        // Prefer non-webp originals, then non-webp thumbs, then webp as fallback
        return $original ?? $thumbnail ?? $webpOriginal ?? $webpThumb;
    }

    /**
     * Remove a bare-ID folder if it's empty or only contains WebP files
     *
     * @param   string  $absDir  Absolute path to the bare-ID folder
     *
     * @return  void
     *
     * @since 10.1.0
     */
    private static function cleanupBareIdFolder(string $absDir): void
    {
        $remaining = @scandir($absDir);

        if ($remaining === false) {
            return;
        }

        // Delete any leftover files (old thumbs, WebP variants, index.html)
        foreach ($remaining as $file) {
            if ($file === '.' || $file === '..') {
                continue;
            }

            @unlink($absDir . '/' . $file);
        }

        // Remove the now-empty directory
        self::removeDirIfEmpty($absDir);
    }

    /**
     * Remove a directory if it contains only index.html or is truly empty
     *
     * Joomla creates index.html files in directories to prevent directory listing.
     * After all real files are deleted, this stub should be cleaned up too.
     *
     * @param   string  $absDir  Absolute path to the directory
     *
     * @return  void
     *
     * @since 10.1.0
     */
    private static function removeDirIfEmpty(string $absDir): void
    {
        if (!is_dir($absDir)) {
            return;
        }

        $remaining = @scandir($absDir);

        if ($remaining === false) {
            return;
        }

        // Filter out . and ..
        $real = array_filter($remaining, fn ($f) => $f !== '.' && $f !== '..');

        // Empty directory — remove it
        if (\count($real) === 0) {
            Folder::delete($absDir);

            return;
        }

        // Only index.html (Joomla directory listing guard) — delete it and remove dir
        if ($real === ['index.html'] || array_values($real) === ['index.html']) {
            @unlink($absDir . '/index.html');
            Folder::delete($absDir);
        }
    }

    /**
     * Search the images directory tree for a file by name
     *
     * Looks in the configured image folder and common locations to find a file
     * that matches the given filename. This handles the old naming convention
     * where images were stored as bare filenames without record IDs.
     *
     * @param   string  $filename  The filename to search for (e.g., 'sermon-title.jpg')
     * @param   string  $type      Record type for folder hints: 'studies', 'teachers', 'series'
     *
     * @return  ?string  Relative path from JPATH_ROOT if found, null otherwise
     *
     * @since 10.2.0
     */
    private static function findImageFile(string $filename, string $type): ?string
    {
        if (empty($filename)) {
            return null;
        }

        // Skip generic filenames that could match unrelated files
        $nameWithoutExt = pathinfo($filename, PATHINFO_FILENAME);
        $genericNames   = [
            'image', 'images', 'photo', 'picture', 'pic', 'img',
            'thumbnail', 'thumb', 'default', 'placeholder', 'no-image',
            'noimage', 'blank', 'sample', 'test', 'temp', 'untitled',
            'new', 'file', 'upload', 'download', 'icon', 'logo', 'banner',
        ];

        if (\in_array(strtolower($nameWithoutExt), $genericNames, true)) {
            return null;
        }

        // Configured image folders per type
        $folderKeys = [
            'studies'  => 'image_folder',
            'teachers' => 'teacher_image_folder',
            'series'   => 'series_image_folder',
        ];
        $folderKey     = $folderKeys[$type] ?? 'image_folder';
        $configuredDir = Cwmparams::getAdmin()->params->get($folderKey, 'images');

        // Directories to search, in priority order
        $searchDirs = [
            JPATH_ROOT . '/' . $configuredDir,
            JPATH_ROOT . '/images',
            JPATH_ROOT . '/images/biblestudy',
            JPATH_ROOT . '/images/biblestudy/' . $type,
            JPATH_ROOT . '/media/com_proclaim/images',
            JPATH_ROOT . '/media/com_proclaim/images/stockimages',
        ];

        // De-duplicate
        $searchDirs = array_unique(array_map(fn ($d) => rtrim($d, '/'), $searchDirs));

        foreach ($searchDirs as $dir) {
            if (!is_dir($dir)) {
                continue;
            }

            // Direct match in this directory
            $candidate = $dir . '/' . $filename;
            if (is_file($candidate)) {
                return self::makeRelative($candidate);
            }

            // Recursive search one level deep (subdirectories)
            $subDirs = Folder::folders($dir, '.', false, true);
            foreach ($subDirs as $subDir) {
                $candidate = $subDir . '/' . $filename;
                if (is_file($candidate)) {
                    return self::makeRelative($candidate);
                }
            }
        }

        return null;
    }

    /**
     * Convert an absolute path to a JPATH_ROOT-relative path
     *
     * @param   string  $absPath  Absolute filesystem path
     *
     * @return  string  Path relative to JPATH_ROOT
     *
     * @since 10.2.0
     */
    private static function makeRelative(string $absPath): string
    {
        $root = rtrim(JPATH_ROOT, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;

        if (str_starts_with($absPath, $root)) {
            return substr($absPath, \strlen($root));
        }

        return $absPath;
    }

    /**
     * Scan legacy image folders for leftover files after migration
     *
     * Checks the old folder locations from com_biblestudy/com_proclaim history
     * and reports any image files still present that are NOT inside the new
     * structured folders (images/biblestudy/{type}/{alias}-{id}/).
     *
     * @return array{folders: array<string, array{path: string, files: int, size: int, filenames: list<string>}>, total_files: int, total_size: int}
     *
     * @since 10.2.0
     */
    public static function getLegacyFolderReport(): array
    {
        $report = ['folders' => [], 'total_files' => 0, 'total_size' => 0];

        // Legacy locations specific to BibleStudy/Proclaim — never scan the
        // root images/ folder since that belongs to the entire Joomla site
        $admin         = Cwmparams::getAdmin();
        $imageFolder   = $admin->params->get('image_folder', 'images');
        $teacherFolder = $admin->params->get('teacher_image_folder', 'images');
        $seriesFolder  = $admin->params->get('series_image_folder', 'images');

        // Only include configured folders if they're Proclaim-specific (not the root images/)
        $genericRoots   = ['images', 'media'];
        $candidates     = [$imageFolder, $teacherFolder, $seriesFolder];
        $configuredDirs = array_filter(
            $candidates,
            fn ($d) => !\in_array(rtrim($d, '/'), $genericRoots, true)
        );

        // Note: media/com_proclaim/images/ is excluded — it contains core component
        // images (icons, logos, defaults) that must never be treated as legacy files.
        $legacyDirs = array_unique(array_filter(array_merge(
            $configuredDirs,
            [
                'images/biblestudy',
            ]
        )));

        // New structured folder pattern — skip these
        $newPattern = '#^images/biblestudy/(studies|teachers|series)/[^/]+-\d+/#';

        $imageExts = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'svg'];

        foreach ($legacyDirs as $relDir) {
            $absDir = JPATH_ROOT . '/' . $relDir;

            if (!is_dir($absDir)) {
                continue;
            }

            // Collect image files directly in this folder (not in subdirs)
            // Exclude any that are core component images
            $directFiles = array_filter(
                self::getImageFilesInDir($absDir, $imageExts),
                fn ($f) => !self::isCoreImage($relDir . '/' . basename($f))
            );

            if (!empty($directFiles)) {
                $size                = array_sum(array_map(fn ($f) => filesize($f), $directFiles));
                $report['folders'][] = [
                    'path'      => $relDir,
                    'files'     => \count($directFiles),
                    'size'      => $size,
                    'filenames' => array_map('basename', $directFiles),
                ];
                $report['total_files'] += \count($directFiles);
                $report['total_size'] += $size;
            }

            // Check subdirectories — but skip new structured folders
            $subDirs = Folder::folders($absDir, '.', false, true);
            foreach ($subDirs as $subDir) {
                $relSub = self::makeRelative($subDir);

                // Skip if it matches the new folder pattern (alias-ID)
                if (preg_match($newPattern, $relSub . '/')) {
                    continue;
                }

                // Skip non-image directories (media, etc.)
                $subName = basename($subDir);
                if (\in_array($subName, ['media', 'studies', 'teachers', 'series'], true)) {
                    // Check inside these for loose files (not in alias-ID subfolders)
                    $looseFiles = self::getImageFilesInDir($subDir, $imageExts);
                    if (!empty($looseFiles)) {
                        $size                = array_sum(array_map(fn ($f) => filesize($f), $looseFiles));
                        $report['folders'][] = [
                            'path'      => $relSub,
                            'files'     => \count($looseFiles),
                            'size'      => $size,
                            'filenames' => array_map('basename', $looseFiles),
                        ];
                        $report['total_files'] += \count($looseFiles);
                        $report['total_size'] += $size;
                    }

                    continue;
                }

                $files = self::getImageFilesInDir($subDir, $imageExts);
                if (!empty($files)) {
                    $size                = array_sum(array_map(fn ($f) => filesize($f), $files));
                    $report['folders'][] = [
                        'path'      => $relSub,
                        'files'     => \count($files),
                        'size'      => $size,
                        'filenames' => array_map('basename', $files),
                    ];
                    $report['total_files'] += \count($files);
                    $report['total_size'] += $size;
                }
            }
        }

        return $report;
    }

    /**
     * Get image files directly in a directory (non-recursive)
     *
     * @param   string  $dir   Absolute directory path
     * @param   array   $exts  Allowed extensions
     *
     * @return  list<string>  Absolute paths of image files found
     *
     * @since 10.2.0
     */
    private static function getImageFilesInDir(string $dir, array $exts): array
    {
        $pattern = '\\.(' . implode('|', $exts) . ')$';

        try {
            return Folder::files($dir, $pattern, false, true) ?: [];
        } catch (\Exception $e) {
            return [];
        }
    }

    /**
     * Delete legacy image files from selected folders
     *
     * Only deletes image files directly in the folder (not recursive).
     * Removes the folder afterwards if it becomes empty.
     * Validates paths are within known Proclaim image directories.
     *
     * @param   array  $folderPaths  Relative paths (e.g. 'images/biblestudy/123')
     *
     * @return  array{deleted: int, errors: list<string>}
     *
     * @since 10.1.0
     */
    public static function deleteLegacyFiles(array $folderPaths): array
    {
        $deleted = 0;
        $errors  = [];

        // Allowed base paths for safety — never delete outside Proclaim dirs
        $allowedBases = [
            'images/biblestudy',
            'media/com_proclaim/images',
        ];

        $imageExts = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'svg'];

        foreach ($folderPaths as $relPath) {
            $relPath = trim($relPath, '/');

            // SAFETY: Validate path is within allowed scope
            $isAllowed = false;

            foreach ($allowedBases as $base) {
                if ($relPath === $base || str_starts_with($relPath, $base . '/')) {
                    $isAllowed = true;
                    break;
                }
            }

            if (!$isAllowed) {
                $errors[] = 'Path not allowed: ' . $relPath;
                continue;
            }

            $absDir = Path::clean(JPATH_ROOT . '/' . $relPath);

            if (!is_dir($absDir)) {
                $errors[] = 'Folder not found: ' . $relPath;
                continue;
            }

            // Delete only image files directly in this folder
            $files         = self::getImageFilesInDir($absDir, $imageExts);
            $folderDeleted = 0;

            foreach ($files as $file) {
                if (@unlink($file)) {
                    $folderDeleted++;
                } else {
                    $errors[] = 'Failed to delete: ' . self::makeRelative($file);
                }
            }

            $deleted += $folderDeleted;

            // Remove index.html and the folder itself if nothing else remains
            self::removeDirIfEmpty($absDir);
        }

        return ['deleted' => $deleted, 'errors' => $errors];
    }

    /**
     * Get count of images needing WebP conversion
     *
     * Scans image directories for JPEG/PNG files that lack a WebP sibling.
     *
     * @return array{studies: int, teachers: int, series: int, total: int}
     *
     * @since 10.1.0
     */
    public static function getWebPMigrationCounts(): array
    {
        $baseDirs = [
            'studies'  => JPATH_ROOT . '/images/biblestudy/studies',
            'teachers' => JPATH_ROOT . '/images/biblestudy/teachers',
            'series'   => JPATH_ROOT . '/images/biblestudy/series',
        ];

        $counts = ['studies' => 0, 'teachers' => 0, 'series' => 0];

        foreach ($baseDirs as $type => $baseDir) {
            if (!is_dir($baseDir)) {
                continue;
            }

            $subDirs = Folder::folders($baseDir, '.', false, true);

            foreach ($subDirs as $dir) {
                $files = Folder::files($dir, '\.(jpe?g|png)$', false, true);

                foreach ($files as $file) {
                    $webpSibling = preg_replace('/\.(jpe?g|png)$/i', '.webp', $file);

                    if (!is_file($webpSibling)) {
                        $counts[$type]++;
                    }
                }
            }
        }

        $counts['total'] = $counts['studies'] + $counts['teachers'] + $counts['series'];

        return $counts;
    }

    /**
     * Generate WebP variants for a batch of images in a given type directory
     *
     * @param   string  $type   Directory type: 'studies', 'teachers', or 'series'
     * @param   int     $limit  Maximum images to process per batch
     *
     * @return array{converted: int, errors: int, remaining: int}
     *
     * @since 10.1.0
     */
    public static function migrateToWebP(string $type, int $limit = 10): array
    {
        $baseDir = JPATH_ROOT . '/images/biblestudy/' . $type;
        $result  = ['converted' => 0, 'errors' => 0, 'remaining' => 0, 'errorFiles' => []];

        if (!is_dir($baseDir) || !\function_exists('imagewebp')) {
            return $result;
        }

        $subDirs   = Folder::folders($baseDir, '.', false, true);
        $processed = 0;
        $total     = 0;

        foreach ($subDirs as $dir) {
            $files = Folder::files($dir, '\.(jpe?g|png)$', false, true);

            foreach ($files as $file) {
                $webpPath = preg_replace('/\.(jpe?g|png)$/i', '.webp', $file);

                if (is_file($webpPath)) {
                    continue;
                }

                $total++;

                if ($processed >= $limit) {
                    $result['remaining']++;
                    continue;
                }

                try {
                    $image = new Image($file);
                    $image->toFile($webpPath, IMAGETYPE_WEBP);

                    // Verify the WebP file is a valid image
                    if (!is_file($webpPath) || filesize($webpPath) === 0) {
                        @unlink($webpPath);
                        throw new \RuntimeException('Output file is empty or missing');
                    }

                    $info = @getimagesize($webpPath);

                    if ($info === false || ($info[0] ?? 0) === 0) {
                        @unlink($webpPath);
                        throw new \RuntimeException('Output file is not a valid image');
                    }

                    $result['converted']++;
                } catch (\Exception $e) {
                    $result['errors']++;
                    $result['errorFiles'][] = self::makeRelative($file) . ': ' . $e->getMessage();
                }

                $processed++;
            }
        }

        // Count remaining across all not-yet-scanned dirs
        $result['remaining'] = $total - $processed;

        return $result;
    }

    /**
     * Get count of records eligible for thumbnail/WebP regeneration per type
     *
     * Counts all records that have a user-uploaded image (excludes core component images).
     *
     * @return array{studies: int, teachers: int, series: int, total: int}
     *
     * @since 10.1.0
     */
    public static function getThumbRegenerationCounts(): array
    {
        $db     = Factory::getContainer()->get('DatabaseDriver');
        $counts = [];

        foreach (self::REGEN_TYPE_CONFIG as $type => $cfg) {
            $query = $db->getQuery(true)
                ->select('COUNT(*)')
                ->from($db->quoteName($cfg['table']));

            self::addUserImageWhereClause($query, $db, $cfg['imageCol'], $cfg['thumbCol']);

            $counts[$type] = (int) $db->setQuery($query)->loadResult();
        }

        $counts['total'] = $counts['studies'] + $counts['teachers'] + $counts['series'];

        return $counts;
    }

    /**
     * Add WHERE clauses to select only records with user-uploaded images
     *
     * Includes records that have a non-empty image or thumbnail, but excludes
     * records whose image paths point to core component images.
     *
     * @param   \Joomla\Database\DatabaseQuery     $query     Query to modify
     * @param   \Joomla\Database\DatabaseInterface  $db       Database driver
     * @param   string                              $imageCol  Image column name
     * @param   string                              $thumbCol  Thumbnail column name
     *
     * @return  void
     *
     * @since 10.1.0
     */
    private static function addUserImageWhereClause(
        \Joomla\Database\DatabaseQuery $query,
        \Joomla\Database\DatabaseInterface $db,
        string $imageCol = 'image',
        string $thumbCol = 'thumbnailm'
    ): void {
        $coreLike = $db->quote(self::CORE_IMAGE_DIR . '/%');

        $query->extendWhere(
            'AND',
            [
                '(' . $db->quoteName($imageCol) . ' IS NOT NULL AND '
                    . $db->quoteName($imageCol) . ' != ' . $db->quote('')
                    . ' AND ' . $db->quoteName($imageCol) . ' NOT LIKE ' . $coreLike . ')',
                '(' . $db->quoteName($thumbCol) . ' IS NOT NULL AND '
                    . $db->quoteName($thumbCol) . ' != ' . $db->quote('')
                    . ' AND ' . $db->quoteName($thumbCol) . ' NOT LIKE ' . $coreLike . ')',
            ],
            'OR'
        );
    }

    /**
     * Force-regenerate thumbnails and WebP variants for a batch of records
     *
     * Reads each record's image column (or derives original from the thumbnail column),
     * creates a fresh thumbnail at the configured size, and generates WebP
     * variants for both the original and the thumbnail.  Always overwrites
     * existing files.
     *
     * @param   string  $type    Record type: 'studies', 'teachers', or 'series'
     * @param   int     $limit   Maximum records to process per batch
     * @param   int     $offset  Offset to resume from
     *
     * @return array{processed: int, errors: int, remaining: int, errorDetails: array}
     *
     * @since 10.1.0
     */
    public static function regenerateThumbnails(
        string $type = 'studies',
        int $limit = 10,
        int $offset = 0,
        int $sizeOverride = 0
    ): array {
        $cfg = self::REGEN_TYPE_CONFIG[$type] ?? null;

        if ($cfg === null) {
            return ['processed' => 0, 'errors' => 0, 'remaining' => 0, 'errorDetails' => ['Invalid type: ' . $type]];
        }

        $db     = Factory::getContainer()->get('DatabaseDriver');
        $params = Cwmparams::getAdmin()->params;
        $size   = $sizeOverride > 0 ? $sizeOverride : (int) $params->get($cfg['sizeParam'], $cfg['sizeDefault']);
        $result = ['processed' => 0, 'errors' => 0, 'remaining' => 0, 'errorDetails' => []];

        // Build column list to select
        $selectCols = ['id', $cfg['imageCol'], $cfg['thumbCol']];

        $query = $db->getQuery(true)
            ->select($db->quoteName($selectCols))
            ->from($db->quoteName($cfg['table']));

        self::addUserImageWhereClause($query, $db, $cfg['imageCol'], $cfg['thumbCol']);
        $query->order($db->quoteName('id'));

        $db->setQuery($query, $offset, $limit);
        $records = $db->loadObjectList();

        // Count total
        $countQuery = $db->getQuery(true)
            ->select('COUNT(*)')
            ->from($db->quoteName($cfg['table']));

        self::addUserImageWhereClause($countQuery, $db, $cfg['imageCol'], $cfg['thumbCol']);
        $totalCount          = (int) $db->setQuery($countQuery)->loadResult();
        $result['remaining'] = max(0, $totalCount - $offset - \count($records));

        $imageCol = $cfg['imageCol'];
        $thumbCol = $cfg['thumbCol'];

        foreach ($records as $record) {
            // Skip if both paths are core images (belt-and-suspenders with SQL filter)
            if (self::isCoreImage($record->$imageCol ?? '') && self::isCoreImage($record->$thumbCol ?? '')) {
                continue;
            }

            // Resolve the original image path — prefer image column, derive from thumbnail
            $imagePath = self::resolveOriginalImage($record, $imageCol, $thumbCol);

            if ($imagePath === null) {
                $result['errors']++;
                $result['errorDetails'][] = 'No original found (' . $type . ' id=' . $record->id . ')';
                continue;
            }

            try {
                $dir          = \dirname($imagePath);
                $baseName     = pathinfo($imagePath, PATHINFO_FILENAME);
                $relDir       = self::absoluteToRelative($dir);
                $thumbPath    = $dir . '/thumb_' . $baseName . '.jpg';
                $thumbRelPath = $relDir . '/thumb_' . $baseName . '.jpg';
                $imageRelPath = $relDir . '/' . basename($imagePath);

                // Generate thumbnail
                $image     = new Image($imagePath);
                $thumbnail = $image->resize($size, (int) round($size * 0.5625), true, Image::SCALE_INSIDE);
                $thumbnail->toFile($thumbPath, IMAGETYPE_JPEG);

                // Always regenerate WebP variants
                if (\function_exists('imagewebp')) {
                    $webpThumbPath = $dir . '/thumb_' . $baseName . '.webp';
                    $thumbnail->toFile($webpThumbPath, IMAGETYPE_WEBP);

                    $ext = strtolower(pathinfo($imagePath, PATHINFO_EXTENSION));

                    if ($ext !== 'webp') {
                        $webpOrigPath = $dir . '/' . $baseName . '.webp';
                        $fullImage    = new Image($imagePath);
                        $fullImage->toFile($webpOrigPath, IMAGETYPE_WEBP);
                    }
                }

                // Update DB columns
                $update = $db->getQuery(true)
                    ->update($db->quoteName($cfg['table']))
                    ->set($db->quoteName($imageCol) . ' = ' . $db->quote($imageRelPath))
                    ->set($db->quoteName($thumbCol) . ' = ' . $db->quote($thumbRelPath))
                    ->where($db->quoteName('id') . ' = ' . (int) $record->id);

                // Teachers also store original path in teacher_image
                if (!empty($cfg['extraImageCol'])) {
                    $update->set($db->quoteName($cfg['extraImageCol']) . ' = ' . $db->quote($imageRelPath));
                }

                $db->setQuery($update)->execute();

                $result['processed']++;
            } catch (\Throwable $e) {
                $result['errors']++;
                $result['errorDetails'][] = $type . ' id=' . $record->id . ': ' . $e->getMessage();
            }
        }

        return $result;
    }

    /**
     * Resolve the absolute path to the original image for a record
     *
     * Prefers the image column.  Falls back to deriving from the thumbnail column
     * by stripping the thumb_ prefix and trying multiple extensions.
     *
     * @param   object  $record    DB row object
     * @param   string  $imageCol  Column name for original image path
     * @param   string  $thumbCol  Column name for thumbnail path
     *
     * @return  string|null  Absolute path on disk, or null if not found
     *
     * @since 10.1.0
     */
    private static function resolveOriginalImage(
        object $record,
        string $imageCol = 'image',
        string $thumbCol = 'thumbnailm'
    ): ?string {
        // Try image column first
        if (!empty($record->$imageCol)) {
            $path = Path::clean(JPATH_ROOT . '/' . $record->$imageCol);

            if (is_file($path)) {
                return $path;
            }

            // Image column might have wrong extension (migration artefact) — try alternatives
            $dir  = \dirname($path);
            $name = pathinfo($path, PATHINFO_FILENAME);

            foreach (['jpg', 'jpeg', 'png', 'webp', 'gif'] as $ext) {
                $candidate = $dir . '/' . $name . '.' . $ext;

                if (is_file($candidate)) {
                    return $candidate;
                }
            }
        }

        // Derive from thumbnail column by stripping thumb_ prefix
        if (!empty($record->$thumbCol)) {
            $thumbBase = basename($record->$thumbCol);

            if (str_starts_with($thumbBase, 'thumb_')) {
                $dir          = Path::clean(JPATH_ROOT . '/' . \dirname($record->$thumbCol));
                $strippedName = pathinfo(substr($thumbBase, 6), PATHINFO_FILENAME);

                foreach (['jpg', 'jpeg', 'png', 'webp', 'gif'] as $ext) {
                    $candidate = $dir . '/' . $strippedName . '.' . $ext;

                    if (is_file($candidate)) {
                        return $candidate;
                    }
                }
            }
        }

        return null;
    }

    /**
     * Convert an absolute path to a JPATH_ROOT-relative path
     *
     * @param   string  $absolutePath  Absolute filesystem path
     *
     * @return  string  Relative path (forward slashes, no leading slash)
     *
     * @since 10.1.0
     */
    private static function absoluteToRelative(string $absolutePath): string
    {
        $root = Path::clean(JPATH_ROOT);

        return ltrim(str_replace($root, '', Path::clean($absolutePath)), '/\\');
    }
}
